In [1]:
# Libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
"""
# Data Access
car_data = pd.read_csv("C:/Users/yunus/Downloads/Dataset-f1/ocean_data_challenge_F1_data/races_2024/car_data_2024.csv")
circuit_data = pd.read_csv("C:/Users/yunus/Downloads/Dataset-f1/ocean_data_challenge_F1_data/races_2024/circuit_2024.csv")
control_message_data = pd.read_csv("C:/Users/yunus/Downloads/Dataset-f1/ocean_data_challenge_F1_data/races_2024/control_message_2024.csv")
lap_data = pd.read_csv("C:/Users/yunus/Downloads/Dataset-f1/ocean_data_challenge_F1_data/races_2024/lap_2024.csv", low_memory=False)
position_data = pd.read_csv("C:/Users/yunus/Downloads/Dataset-f1/ocean_data_challenge_F1_data/races_2024/position_2024.csv")
result_data = pd.read_csv("C:/Users/yunus/Downloads/Dataset-f1/ocean_data_challenge_F1_data/races_2024/result_2024.csv")
session_status_data = pd.read_csv("C:/Users/yunus/Downloads/Dataset-f1/ocean_data_challenge_F1_data/races_2024/session_status_2024.csv")
track_status_data = pd.read_csv("C:/Users/yunus/Downloads/Dataset-f1/ocean_data_challenge_F1_data/races_2024/track_status_2024.csv")
weather_data = pd.read_csv("C:/Users/yunus/Downloads/Dataset-f1/ocean_data_challenge_F1_data/races_2024/weather_2024.csv")
"""

In [3]:
# Race Data Access
race_car_data = pd.read_csv("C:/Users/yunus/Downloads/Mexican GP Data Challenge Datasets/ocean_mexican_gp_data_challenge_datasets/mexican_gp_race_datasets_2018-2019-2021-2022-2023/car_data_mexico_grand_prix_2018-2019-2021-2022-2023.csv")
race_circuit_data = pd.read_csv("C:/Users/yunus/Downloads/Mexican GP Data Challenge Datasets/ocean_mexican_gp_data_challenge_datasets/mexican_gp_race_datasets_2018-2019-2021-2022-2023/circuit_mexico_grand_prix_2018-2019-2021-2022-2023.csv")
race_control_message_data = pd.read_csv("C:/Users/yunus/Downloads/Mexican GP Data Challenge Datasets/ocean_mexican_gp_data_challenge_datasets/mexican_gp_race_datasets_2018-2019-2021-2022-2023/control_message_mexico_grand_prix_2018-2019-2021-2022-2023.csv")
race_lap_data = pd.read_csv("C:/Users/yunus/Downloads/Mexican GP Data Challenge Datasets/ocean_mexican_gp_data_challenge_datasets/mexican_gp_race_datasets_2018-2019-2021-2022-2023/lap_mexico_grand_prix_2018-2019-2021-2022-2023.csv", low_memory=False)
race_position_data = pd.read_csv("C:/Users/yunus/Downloads/Mexican GP Data Challenge Datasets/ocean_mexican_gp_data_challenge_datasets/mexican_gp_race_datasets_2018-2019-2021-2022-2023/position_mexico_grand_prix_2018-2019-2021-2022-2023.csv")
race_result_data = pd.read_csv("C:/Users/yunus/Downloads/Mexican GP Data Challenge Datasets/ocean_mexican_gp_data_challenge_datasets/mexican_gp_race_datasets_2018-2019-2021-2022-2023/result_mexico_grand_prix_2018-2019-2021-2022-2023.csv")
race_session_status_data = pd.read_csv("C:/Users/yunus/Downloads/Mexican GP Data Challenge Datasets/ocean_mexican_gp_data_challenge_datasets/mexican_gp_race_datasets_2018-2019-2021-2022-2023/session_status_mexico_grand_prix_2018-2019-2021-2022-2023.csv")
race_track_status_data = pd.read_csv("C:/Users/yunus/Downloads/Mexican GP Data Challenge Datasets/ocean_mexican_gp_data_challenge_datasets/mexican_gp_race_datasets_2018-2019-2021-2022-2023/track_status_mexico_grand_prix_2018-2019-2021-2022-2023.csv")
race_weather_data = pd.read_csv("C:/Users/yunus/Downloads/Mexican GP Data Challenge Datasets/ocean_mexican_gp_data_challenge_datasets/mexican_gp_race_datasets_2018-2019-2021-2022-2023/weather_mexico_grand_prix_2018-2019-2021-2022-2023.csv")

In [5]:
# Data Merge
# 4. lap_data
# Extract days and hours
race_lap_data['Days'] = race_lap_data['Time'].apply(lambda x: int(x.split(' ')[0]))
race_lap_data['Hours'] = race_lap_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[0]))
race_lap_data['Minutes'] = race_lap_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[1]))

# View the updated DataFrame
print(race_lap_data)

      Year                    Time Driver  DriverNumber  \
0     2018  0 days 00:34:35.418000    GAS            10
1     2018  0 days 00:36:01.984000    GAS            10
2     2018  0 days 00:37:26.860000    GAS            10
3     2018  0 days 00:38:54.567000    GAS            10
4     2018  0 days 00:40:38.975000    GAS            10
...    ...                     ...    ...           ...
6532  2023  0 days 02:59:59.540000    PIA            81
6533  2023  0 days 03:01:22.902000    PIA            81
6534  2023  0 days 03:02:46.070000    PIA            81
6535  2023  0 days 03:04:09.050000    PIA            81
6536  2023  0 days 03:05:32.471000    PIA            81

                     LapTime  LapNumber  Stint PitOutTime  \
0     0 days 00:01:36.516000        1.0    1.0        NaN
1     0 days 00:01:26.566000        2.0    1.0        NaN
2     0 days 00:01:24.876000        3.0    1.0        NaN
3     0 days 00:01:27.707000        4.0    1.0        NaN
4     0 days 00:01:44.408000        5.0    1.0        NaN
...                      ...        ...    ...        ...
6532  0 days 00:01:23.238000       67.0    3.0        NaN
6533  0 days 00:01:23.362000       68.0    3.0        NaN
6534  0 days 00:01:23.168000       69.0    3.0        NaN
6535  0 days 00:01:22.980000       70.0    3.0        NaN
6536  0 days 00:01:23.421000       71.0    3.0        NaN

                   PitInTime             Sector1Time  ...  \
0                        NaN                     NaN  ...
1                        NaN  0 days 00:00:29.676000  ...
2                        NaN  0 days 00:00:29.359000  ...
3                        NaN  0 days 00:00:30.540000  ...
4     0 days 00:40:36.342000  0 days 00:00:41.052000  ...
...                      ...                     ...  ...
6532                     NaN  0 days 00:00:29.080000  ...
6533                     NaN  0 days 00:00:29.140000  ...
6534                     NaN  0 days 00:00:29.060000  ...
6535                     NaN  0 days 00:00:29.112000  ...
6536                     NaN  0 days 00:00:29.165000  ...

                 LapStartDate TrackStatus Position Deleted DeletedReason  \
0     2018-10-28 19:12:58.805           1     17.0   False           NaN
1     2018-10-28 19:14:35.520           1     16.0   False           NaN
2     2018-10-28 19:16:02.086           1     16.0   False           NaN
3     2018-10-28 19:17:26.962          12     17.0   False           NaN
4     2018-10-28 19:18:54.669        2671     17.0   False           NaN
...                       ...         ...      ...     ...           ...
6532  2023-10-29 21:59:36.383          12      8.0   False           NaN
6533  2023-10-29 22:00:59.621           1      8.0   False           NaN
6534  2023-10-29 22:02:22.983           1      8.0   False           NaN
6535  2023-10-29 22:03:46.151           1      8.0   False           NaN
6536  2023-10-29 22:05:09.131           1      8.0   False           NaN

      FastF1Generated  IsAccurate  Days  Hours Minutes
0               False       False     0      0      34
1               False        True     0      0      36
2               False        True     0      0      37
3               False        True     0      0      38
4               False       False     0      0      40
...               ...         ...   ...    ...     ...
6532            False        True     0      2      59
6533            False        True     0      3       1
6534            False        True     0      3       2
6535            False        True     0      3       4
6536            False        True     0      3       5

[6537 rows x 35 columns]

In [7]:
# Extract days and hours
race_weather_data['Days'] = race_weather_data['Time'].apply(lambda x: int(x.split(' ')[0]))
race_weather_data['Hours'] = race_weather_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[0]))
race_weather_data['Minutes'] = race_weather_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[1]))

# View the updated DataFrame
print(race_weather_data)

     Year                    Time  AirTemp  Humidity  Pressure  Rainfall  \
0    2018  0 days 00:00:04.381000     19.2      53.9     785.1     False
1    2018  0 days 00:01:04.395000     19.2      53.9     785.1     False
2    2018  0 days 00:02:04.409000     19.2      54.1     785.0     False
3    2018  0 days 00:03:04.425000     19.1      54.9     785.0     False
4    2018  0 days 00:04:04.438000     19.1      54.4     785.1     False
..    ...                     ...      ...       ...       ...       ...
784  2023  0 days 03:05:53.455000     26.2      19.0     778.5     False
785  2023  0 days 03:06:53.454000     26.1      19.0     778.7     False
786  2023  0 days 03:07:53.453000     26.2      19.0     778.7     False
787  2023  0 days 03:08:53.483000     26.1      19.0     778.7     False
788  2023  0 days 03:09:53.482000     26.0      19.0     778.5     False

     TrackTemp  WindDirection  WindSpeed  Days  Hours  Minutes
0         35.2            284        2.3     0      0        0
1         35.2            284        2.3     0      0        1
2         35.2            308        3.1     0      0        2
3         35.6            282        2.2     0      0        3
4         35.5            277        2.6     0      0        4
..         ...            ...        ...   ...    ...      ...
784       37.0            281        1.5     0      3        5
785       36.6            268        2.9     0      3        6
786       36.5            288        2.7     0      3        7
787       36.2              0        2.0     0      3        8
788       35.9            203        0.5     0      3        9

[789 rows x 12 columns]

In [11]:
# Remove duplicates in weather_data based on 'eventname' and 'hours'
race_weather_data1 = race_weather_data.drop_duplicates(subset=['Year', 'Hours', 'Minutes'])

# Now perform the left join
race_lap_data1 = pd.merge(race_lap_data, race_weather_data1, on=['Year', 'Hours', 'Minutes'], how='left')

# The number of rows in merged_df should now match df1

print(race_lap_data1)

      Year                  Time_x Driver  DriverNumber  \
0     2018  0 days 00:34:35.418000    GAS            10
1     2018  0 days 00:36:01.984000    GAS            10
2     2018  0 days 00:37:26.860000    GAS            10
3     2018  0 days 00:38:54.567000    GAS            10
4     2018  0 days 00:40:38.975000    GAS            10
...    ...                     ...    ...           ...
6532  2023  0 days 02:59:59.540000    PIA            81
6533  2023  0 days 03:01:22.902000    PIA            81
6534  2023  0 days 03:02:46.070000    PIA            81
6535  2023  0 days 03:04:09.050000    PIA            81
6536  2023  0 days 03:05:32.471000    PIA            81

                     LapTime  LapNumber  Stint PitOutTime  \
0     0 days 00:01:36.516000        1.0    1.0        NaN
1     0 days 00:01:26.566000        2.0    1.0        NaN
2     0 days 00:01:24.876000        3.0    1.0        NaN
3     0 days 00:01:27.707000        4.0    1.0        NaN
4     0 days 00:01:44.408000        5.0    1.0        NaN
...                      ...        ...    ...        ...
6532  0 days 00:01:23.238000       67.0    3.0        NaN
6533  0 days 00:01:23.362000       68.0    3.0        NaN
6534  0 days 00:01:23.168000       69.0    3.0        NaN
6535  0 days 00:01:22.980000       70.0    3.0        NaN
6536  0 days 00:01:23.421000       71.0    3.0        NaN

                   PitInTime             Sector1Time  ... Minutes  \
0                        NaN                     NaN  ...      34
1                        NaN  0 days 00:00:29.676000  ...      36
2                        NaN  0 days 00:00:29.359000  ...      37
3                        NaN  0 days 00:00:30.540000  ...      38
4     0 days 00:40:36.342000  0 days 00:00:41.052000  ...      40
...                      ...                     ...  ...     ...
6532                     NaN  0 days 00:00:29.080000  ...      59
6533                     NaN  0 days 00:00:29.140000  ...       1
6534                     NaN  0 days 00:00:29.060000  ...       2
6535                     NaN  0 days 00:00:29.112000  ...       4
6536                     NaN  0 days 00:00:29.165000  ...       5

                      Time_y AirTemp Humidity Pressure  Rainfall  TrackTemp  \
0     0 days 00:34:04.867000    19.2     53.8    784.7     False       32.6
1     0 days 00:36:04.896000    19.4     53.2    784.7     False       33.1
2     0 days 00:37:04.911000    19.3     53.4    784.6     False       33.1
3     0 days 00:38:04.926000    19.5     53.0    784.7     False       32.5
4     0 days 00:40:04.955000    19.5     52.8    784.6     False       33.4
...                      ...     ...      ...      ...       ...        ...
6532  0 days 02:59:53.430000    26.4     19.0    778.5     False       38.7
6533  0 days 03:01:53.428000    26.3     19.0    778.5     False       38.1
6534  0 days 03:02:53.411000    26.3     19.0    778.5     False       37.7
6535  0 days 03:04:53.456000    26.2     19.0    778.5     False       37.3
6536  0 days 03:05:53.455000    26.2     19.0    778.5     False       37.0

      WindDirection  WindSpeed Days_y
0               295        1.6      0
1                83        0.6      0
2               189        1.0      0
3               253        0.7      0
4               273        1.9      0
...             ...        ...    ...
6532            313        1.6      0
6533            303        1.2      0
6534              0        0.8      0
6535            285        1.2      0
6536            281        1.5      0

[6537 rows x 44 columns]

In [13]:
race_lap_data1.head(), race_lap_data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6537 entries, 0 to 6536
Data columns (total 44 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year                6537 non-null   int64
 1   Time_x              6537 non-null   object
 2   Driver              6537 non-null   object
 3   DriverNumber        6537 non-null   int64
 4   LapTime             6500 non-null   object
 5   LapNumber           6537 non-null   float64
 6   Stint               6537 non-null   float64
 7   PitOutTime          143 non-null    object
 8   PitInTime           150 non-null    object
 9   Sector1Time         6411 non-null   object
 10  Sector2Time         6528 non-null   object
 11  Sector3Time         6527 non-null   object
 12  Sector1SessionTime  6397 non-null   object
 13  Sector2SessionTime  6528 non-null   object
 14  Sector3SessionTime  6527 non-null   object
 15  SpeedI1             5941 non-null   float64
 16  SpeedI2             6527 non-null   float64
 17  SpeedFL             6380 non-null   float64
 18  SpeedST             5375 non-null   float64
 19  IsPersonalBest      6532 non-null   object
 20  Compound            6537 non-null   object
 21  TyreLife            6537 non-null   float64
 22  FreshTyre           6537 non-null   bool
 23  Team                6537 non-null   object
 24  LapStartTime        6537 non-null   object
 25  LapStartDate        6532 non-null   object
 26  TrackStatus         6537 non-null   int64
 27  Position            6530 non-null   float64
 28  Deleted             6537 non-null   bool
 29  DeletedReason       12 non-null     object
 30  FastF1Generated     6537 non-null   bool
 31  IsAccurate          6537 non-null   bool
 32  Days_x              6537 non-null   int64
 33  Hours               6537 non-null   int64
 34  Minutes             6537 non-null   int64
 35  Time_y              6537 non-null   object
 36  AirTemp             6537 non-null   float64
 37  Humidity            6537 non-null   float64
 38  Pressure            6537 non-null   float64
 39  Rainfall            6537 non-null   bool
 40  TrackTemp           6537 non-null   float64
 41  WindDirection       6537 non-null   int64
 42  WindSpeed           6537 non-null   float64
 43  Days_y              6537 non-null   int64
dtypes: bool(5), float64(13), int64(8), object(18)
memory usage: 2.0+ MB

(   Year                  Time_x Driver  DriverNumber                 LapTime  \
 0  2018  0 days 00:34:35.418000    GAS            10  0 days 00:01:36.516000
 1  2018  0 days 00:36:01.984000    GAS            10  0 days 00:01:26.566000
 2  2018  0 days 00:37:26.860000    GAS            10  0 days 00:01:24.876000
 3  2018  0 days 00:38:54.567000    GAS            10  0 days 00:01:27.707000
 4  2018  0 days 00:40:38.975000    GAS            10  0 days 00:01:44.408000

    LapNumber  Stint PitOutTime               PitInTime  \
 0        1.0    1.0        NaN                     NaN
 1        2.0    1.0        NaN                     NaN
 2        3.0    1.0        NaN                     NaN
 3        4.0    1.0        NaN                     NaN
 4        5.0    1.0        NaN  0 days 00:40:36.342000

               Sector1Time  ... Minutes                  Time_y AirTemp  \
 0                     NaN  ...      34  0 days 00:34:04.867000    19.2
 1  0 days 00:00:29.676000  ...      36  0 days 00:36:04.896000    19.4
 2  0 days 00:00:29.359000  ...      37  0 days 00:37:04.911000    19.3
 3  0 days 00:00:30.540000  ...      38  0 days 00:38:04.926000    19.5
 4  0 days 00:00:41.052000  ...      40  0 days 00:40:04.955000    19.5

   Humidity Pressure  Rainfall  TrackTemp  WindDirection  WindSpeed Days_y
 0     53.8    784.7     False       32.6            295        1.6      0
 1     53.2    784.7     False       33.1             83        0.6      0
 2     53.4    784.6     False       33.1            189        1.0      0
 3     53.0    784.7     False       32.5            253        0.7      0
 4     52.8    784.6     False       33.4            273        1.9      0

 [5 rows x 44 columns],
 None)

In [15]:
# car_data
# Extract days and hours
race_car_data['Days'] = race_car_data['SessionTime'].apply(lambda x: int(x.split(' ')[0]))
race_car_data['Hours'] = race_car_data['SessionTime'].apply(lambda x: int(x.split(' ')[2].split(':')[0]))
race_car_data['Minutes'] = race_car_data['SessionTime'].apply(lambda x: int(x.split(' ')[2].split(':')[1]))

# View the updated DataFrame
print(race_car_data)

         Year DriverName                     Date    RPM  Speed  nGear  \
0        2018        VER  2018-10-28 19:12:58.809  11499      0      1
1        2018        VER  2018-10-28 19:12:59.049  11393      0      1
2        2018        VER  2018-10-28 19:12:59.289   9993      4      1
3        2018        VER  2018-10-28 19:12:59.529   8313     15      1
4        2018        VER  2018-10-28 19:12:59.769   6773     22      1
...       ...        ...                      ...    ...    ...    ...
2302767  2023        PER  2023-10-29 20:05:00.931   6950     80      2
2302768  2023        PER  2023-10-29 20:05:01.131   7048     80      2
2302769  2023        PER  2023-10-29 20:05:01.371   6958     80      2
2302770  2023        PER  2023-10-29 20:05:01.531   7068     80      2
2302771  2023        PER  2023-10-29 20:05:01.811   6981     80      2

         Throttle  Brake  DRS Source                    Time  \
0              13  False    1    car  0 days 00:00:00.004000
1              13   True    1    car  0 days 00:00:00.244000
2              14  False    1    car  0 days 00:00:00.484000
3              14  False    1    car  0 days 00:00:00.724000
4              16  False    1    car  0 days 00:00:00.964000
...           ...    ...  ...    ...                     ...
2302767       100  False    1    car  0 days 00:01:42.609000
2302768       100  False    1    car  0 days 00:01:42.809000
2302769       100  False    1    car  0 days 00:01:43.049000
2302770       100  False    1    car  0 days 00:01:43.209000
2302771        99  False    1    car  0 days 00:01:43.489000

                    SessionTime  Days  Hours  Minutes
0        0 days 00:32:58.707000     0      0       32
1        0 days 00:32:58.947000     0      0       32
2        0 days 00:32:59.187000     0      0       32
3        0 days 00:32:59.427000     0      0       32
4        0 days 00:32:59.667000     0      0       32
...                         ...   ...    ...      ...
2302767  0 days 01:04:00.850000     0      1        4
2302768  0 days 01:04:01.050000     0      1        4
2302769  0 days 01:04:01.290000     0      1        4
2302770  0 days 01:04:01.450000     0      1        4
2302771  0 days 01:04:01.730000     0      1        4

[2302772 rows x 15 columns]

In [17]:
race_car_data.head(), race_car_data.info(), race_car_data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2302772 entries, 0 to 2302771
Data columns (total 15 columns):
 #   Column       Dtype
---  ------       -----
 0   Year         int64
 1   DriverName   object
 2   Date         object
 3   RPM          int64
 4   Speed        int64
 5   nGear        int64
 6   Throttle     int64
 7   Brake        bool
 8   DRS          int64
 9   Source       object
 10  Time         object
 11  SessionTime  object
 12  Days         int64
 13  Hours        int64
 14  Minutes      int64
dtypes: bool(1), int64(9), object(5)
memory usage: 248.2+ MB

(   Year DriverName                     Date    RPM  Speed  nGear  Throttle  \
 0  2018        VER  2018-10-28 19:12:58.809  11499      0      1        13
 1  2018        VER  2018-10-28 19:12:59.049  11393      0      1        13
 2  2018        VER  2018-10-28 19:12:59.289   9993      4      1        14
 3  2018        VER  2018-10-28 19:12:59.529   8313     15      1        14
 4  2018        VER  2018-10-28 19:12:59.769   6773     22      1        16

    Brake  DRS Source                    Time             SessionTime  Days  \
 0  False    1    car  0 days 00:00:00.004000  0 days 00:32:58.707000     0
 1   True    1    car  0 days 00:00:00.244000  0 days 00:32:58.947000     0
 2  False    1    car  0 days 00:00:00.484000  0 days 00:32:59.187000     0
 3  False    1    car  0 days 00:00:00.724000  0 days 00:32:59.427000     0
 4  False    1    car  0 days 00:00:00.964000  0 days 00:32:59.667000     0

    Hours  Minutes
 0      0       32
 1      0       32
 2      0       32
 3      0       32
 4      0       32  ,
 None,
                Year           RPM         Speed         nGear      Throttle  \
 count  2.302772e+06  2.302772e+06  2.302772e+06  2.302772e+06  2.302772e+06
 mean   2.020642e+03  9.264155e+03  1.726234e+02  4.426694e+00  5.103276e+01
 std    1.867250e+00  2.503548e+03  8.642763e+01  2.188718e+00  4.317976e+01
 min    2.018000e+03  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
 25%    2.019000e+03  7.847000e+03  1.020000e+02  3.000000e+00  0.000000e+00
 50%    2.021000e+03  9.997000e+03  1.610000e+02  4.000000e+00  5.300000e+01
 75%    2.022000e+03  1.113300e+04  2.420000e+02  6.000000e+00  1.000000e+02
 max    2.023000e+03  1.352900e+04  3.700000e+02  4.200000e+01  1.040000e+02

                 DRS       Days         Hours       Minutes
 count  2.302772e+06  2302772.0  2.302772e+06  2.302772e+06
 mean   7.254778e-01        0.0  1.206126e+00  2.874368e+01
 std    2.418907e+00        0.0  6.389984e-01  1.735034e+01
 min    0.000000e+00        0.0  0.000000e+00  0.000000e+00
 25%    0.000000e+00        0.0  1.000000e+00  1.300000e+01
 50%    0.000000e+00        0.0  1.000000e+00  2.900000e+01
 75%    0.000000e+00        0.0  2.000000e+00  4.300000e+01
 max    1.400000e+01        0.0  3.000000e+00  5.900000e+01  )

In [19]:
race_car_data.describe(include='object')

,DriverName,Date,Source,Time,SessionTime
count,2302772,2302772,2302772,2302772,2302772
unique,33,124299,1,123713,123226
top,GAS,2018-10-28 19:12:58.809,car,0 days 00:05:29.809000,0 days 01:21:45.357000
freq,123729,20,2302772,39,40

In [21]:
# Remove duplicates in weather_data based on 'eventname' and 'hours'
race_car_data1 = race_car_data.drop_duplicates(subset=['Year', 'DriverName', 'Hours', 'Minutes'])

In [23]:
race_car_data1.rename(columns={'DriverName': 'Driver'}, inplace=True)

C:\Users\yunus\AppData\Local\Temp\ipykernel_3112\1045484187.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  race_car_data1.rename(columns={'DriverName': 'Driver'}, inplace=True)

In [25]:
race_car_data1.head(), race_car_data1.info(), race_car_data1.describe(), race_car_data1.describe(include='object')

<class 'pandas.core.frame.DataFrame'>
Index: 9746 entries, 0 to 2302764
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Year         9746 non-null   int64
 1   Driver       9746 non-null   object
 2   Date         9746 non-null   object
 3   RPM          9746 non-null   int64
 4   Speed        9746 non-null   int64
 5   nGear        9746 non-null   int64
 6   Throttle     9746 non-null   int64
 7   Brake        9746 non-null   bool
 8   DRS          9746 non-null   int64
 9   Source       9746 non-null   object
 10  Time         9746 non-null   object
 11  SessionTime  9746 non-null   object
 12  Days         9746 non-null   int64
 13  Hours        9746 non-null   int64
 14  Minutes      9746 non-null   int64
dtypes: bool(1), int64(9), object(5)
memory usage: 1.1+ MB

(     Year Driver                     Date    RPM  Speed  nGear  Throttle  \
 0    2018    VER  2018-10-28 19:12:58.809  11499      0      1        13
 6    2018    VER  2018-10-28 19:13:00.249   5749     42      1        34
 252  2018    VER  2018-10-28 19:14:00.290  10576    271      7       100
 500  2018    VER  2018-10-28 19:15:00.291   9270    121      3         0
 746  2018    VER  2018-10-28 19:16:00.212   7777    111      3         0

      Brake  DRS Source                    Time             SessionTime  Days  \
 0    False    1    car  0 days 00:00:00.004000  0 days 00:32:58.707000     0
 6    False    1    car  0 days 00:00:01.444000  0 days 00:33:00.147000     0
 252  False    1    car  0 days 00:01:01.485000  0 days 00:34:00.188000     0
 500   True    1    car  0 days 00:02:01.486000  0 days 00:35:00.189000     0
 746   True    1    car  0 days 00:03:01.407000  0 days 00:36:00.110000     0

      Hours  Minutes
 0        0       32
 6        0       33
 252      0       34
 500      0       35
 746      0       36  ,
 None,
               Year           RPM        Speed        nGear     Throttle  \
 count  9746.000000   9746.000000  9746.000000  9746.000000  9746.000000
 mean   2020.709111   9265.030679   170.697414     4.380361    50.894418
 std       1.873154   2528.433640    88.078874     2.227976    43.139004
 min    2018.000000      0.000000     0.000000     0.000000     0.000000
 25%    2019.000000   7864.250000   101.000000     3.000000     0.000000
 50%    2021.000000  10039.500000   160.000000     4.000000    53.000000
 75%    2022.000000  11135.750000   240.000000     6.000000   100.000000
 max    2023.000000  12937.000000   362.000000    35.000000   104.000000

                DRS    Days        Hours      Minutes
 count  9746.000000  9746.0  9746.000000  9746.000000
 mean      0.745126     0.0     1.217936    28.655038
 std       2.423607     0.0     0.642205    17.329553
 min       0.000000     0.0     0.000000     0.000000
 25%       0.000000     0.0     1.000000    13.000000
 50%       0.000000     0.0     1.000000    29.000000
 75%       0.000000     0.0     2.000000    43.000000
 max      14.000000     0.0     3.000000    59.000000  ,
        Driver                     Date Source                    Time  \
 count    9746                     9746   9746                    9746
 unique     33                      527      1                     527
 top       GAS  2018-10-28 19:12:58.809    car  0 days 00:00:00.004000
 freq      523                       20   9746                      20

                    SessionTime
 count                     9746
 unique                     520
 top     0 days 01:13:00.052000
 freq                        38  )

In [27]:
# Remove duplicates in weather_data based on 'eventname' and 'hours'
# car_data1 = car_data.drop_duplicates(subset=['EventName', 'DriverName', 'Hours', 'Minutes'])

# Now perform the left join
race_lap_data2 = pd.merge(race_lap_data1, race_car_data1, on=['Year', 'Driver', 'Hours', 'Minutes'], how='left')

# The number of rows in merged_df should now match df1

print(race_lap_data2)

      Year                  Time_x Driver  DriverNumber  \
0     2018  0 days 00:34:35.418000    GAS            10
1     2018  0 days 00:36:01.984000    GAS            10
2     2018  0 days 00:37:26.860000    GAS            10
3     2018  0 days 00:38:54.567000    GAS            10
4     2018  0 days 00:40:38.975000    GAS            10
...    ...                     ...    ...           ...
6532  2023  0 days 02:59:59.540000    PIA            81
6533  2023  0 days 03:01:22.902000    PIA            81
6534  2023  0 days 03:02:46.070000    PIA            81
6535  2023  0 days 03:04:09.050000    PIA            81
6536  2023  0 days 03:05:32.471000    PIA            81

                     LapTime  LapNumber  Stint PitOutTime  \
0     0 days 00:01:36.516000        1.0    1.0        NaN
1     0 days 00:01:26.566000        2.0    1.0        NaN
2     0 days 00:01:24.876000        3.0    1.0        NaN
3     0 days 00:01:27.707000        4.0    1.0        NaN
4     0 days 00:01:44.408000        5.0    1.0        NaN
...                      ...        ...    ...        ...
6532  0 days 00:01:23.238000       67.0    3.0        NaN
6533  0 days 00:01:23.362000       68.0    3.0        NaN
6534  0 days 00:01:23.168000       69.0    3.0        NaN
6535  0 days 00:01:22.980000       70.0    3.0        NaN
6536  0 days 00:01:23.421000       71.0    3.0        NaN

                   PitInTime             Sector1Time  ...    RPM Speed nGear  \
0                        NaN                     NaN  ...  10420   176     4
1                        NaN  0 days 00:00:29.676000  ...  11072   211     5
2                        NaN  0 days 00:00:29.359000  ...  11404   198     4
3                        NaN  0 days 00:00:30.540000  ...   6184    91     3
4     0 days 00:40:36.342000  0 days 00:00:41.052000  ...   9926   170     5
...                      ...                     ...  ...    ...   ...   ...
6532                     NaN  0 days 00:00:29.080000  ...  10814   229     6
6533                     NaN  0 days 00:00:29.140000  ...  11021   276     7
6534                     NaN  0 days 00:00:29.060000  ...  10111   103     2
6535                     NaN  0 days 00:00:29.112000  ...   9092   118     3
6536                     NaN  0 days 00:00:29.165000  ...  11292   218     5

     Throttle  Brake  DRS  Source                    Time  \
0           3  False    1     car  0 days 00:01:01.485000
1         100  False    1     car  0 days 00:03:01.407000
2         100  False    0     car  0 days 00:04:01.488000
3           0   True    0     car  0 days 00:05:01.328000
4           0   True    1     car  0 days 00:07:01.370000
...       ...    ...  ...     ...                     ...
6532       98  False    0     car  0 days 01:56:41.911000
6533       98  False    0     car  0 days 01:58:42.032000
6534       69  False    0     car  0 days 01:59:41.912000
6535       69  False    0     car  0 days 02:01:41.952000
6536       47  False    0     car  0 days 02:02:41.912000

                 SessionTime Days
0     0 days 00:34:00.188000    0
1     0 days 00:36:00.110000    0
2     0 days 00:37:00.191000    0
3     0 days 00:38:00.031000    0
4     0 days 00:40:00.073000    0
...                      ...  ...
6532  0 days 02:59:00.152000    0
6533  0 days 03:01:00.273000    0
6534  0 days 03:02:00.153000    0
6535  0 days 03:04:00.193000    0
6536  0 days 03:05:00.153000    0

[6537 rows x 55 columns]

In [29]:
race_lap_data2.head(), race_lap_data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6537 entries, 0 to 6536
Data columns (total 55 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year                6537 non-null   int64
 1   Time_x              6537 non-null   object
 2   Driver              6537 non-null   object
 3   DriverNumber        6537 non-null   int64
 4   LapTime             6500 non-null   object
 5   LapNumber           6537 non-null   float64
 6   Stint               6537 non-null   float64
 7   PitOutTime          143 non-null    object
 8   PitInTime           150 non-null    object
 9   Sector1Time         6411 non-null   object
 10  Sector2Time         6528 non-null   object
 11  Sector3Time         6527 non-null   object
 12  Sector1SessionTime  6397 non-null   object
 13  Sector2SessionTime  6528 non-null   object
 14  Sector3SessionTime  6527 non-null   object
 15  SpeedI1             5941 non-null   float64
 16  SpeedI2             6527 non-null   float64
 17  SpeedFL             6380 non-null   float64
 18  SpeedST             5375 non-null   float64
 19  IsPersonalBest      6532 non-null   object
 20  Compound            6537 non-null   object
 21  TyreLife            6537 non-null   float64
 22  FreshTyre           6537 non-null   bool
 23  Team                6537 non-null   object
 24  LapStartTime        6537 non-null   object
 25  LapStartDate        6532 non-null   object
 26  TrackStatus         6537 non-null   int64
 27  Position            6530 non-null   float64
 28  Deleted             6537 non-null   bool
 29  DeletedReason       12 non-null     object
 30  FastF1Generated     6537 non-null   bool
 31  IsAccurate          6537 non-null   bool
 32  Days_x              6537 non-null   int64
 33  Hours               6537 non-null   int64
 34  Minutes             6537 non-null   int64
 35  Time_y              6537 non-null   object
 36  AirTemp             6537 non-null   float64
 37  Humidity            6537 non-null   float64
 38  Pressure            6537 non-null   float64
 39  Rainfall            6537 non-null   bool
 40  TrackTemp           6537 non-null   float64
 41  WindDirection       6537 non-null   int64
 42  WindSpeed           6537 non-null   float64
 43  Days_y              6537 non-null   int64
 44  Date                6537 non-null   object
 45  RPM                 6537 non-null   int64
 46  Speed               6537 non-null   int64
 47  nGear               6537 non-null   int64
 48  Throttle            6537 non-null   int64
 49  Brake               6537 non-null   bool
 50  DRS                 6537 non-null   int64
 51  Source              6537 non-null   object
 52  Time                6537 non-null   object
 53  SessionTime         6537 non-null   object
 54  Days                6537 non-null   int64
dtypes: bool(6), float64(13), int64(14), object(22)
memory usage: 2.5+ MB

(   Year                  Time_x Driver  DriverNumber                 LapTime  \
 0  2018  0 days 00:34:35.418000    GAS            10  0 days 00:01:36.516000
 1  2018  0 days 00:36:01.984000    GAS            10  0 days 00:01:26.566000
 2  2018  0 days 00:37:26.860000    GAS            10  0 days 00:01:24.876000
 3  2018  0 days 00:38:54.567000    GAS            10  0 days 00:01:27.707000
 4  2018  0 days 00:40:38.975000    GAS            10  0 days 00:01:44.408000

    LapNumber  Stint PitOutTime               PitInTime  \
 0        1.0    1.0        NaN                     NaN
 1        2.0    1.0        NaN                     NaN
 2        3.0    1.0        NaN                     NaN
 3        4.0    1.0        NaN                     NaN
 4        5.0    1.0        NaN  0 days 00:40:36.342000

               Sector1Time  ...    RPM Speed nGear Throttle  Brake  DRS  \
 0                     NaN  ...  10420   176     4        3  False    1
 1  0 days 00:00:29.676000  ...  11072   211     5      100  False    1
 2  0 days 00:00:29.359000  ...  11404   198     4      100  False    0
 3  0 days 00:00:30.540000  ...   6184    91     3        0   True    0
 4  0 days 00:00:41.052000  ...   9926   170     5        0   True    1

    Source                    Time             SessionTime Days
 0     car  0 days 00:01:01.485000  0 days 00:34:00.188000    0
 1     car  0 days 00:03:01.407000  0 days 00:36:00.110000    0
 2     car  0 days 00:04:01.488000  0 days 00:37:00.191000    0
 3     car  0 days 00:05:01.328000  0 days 00:38:00.031000    0
 4     car  0 days 00:07:01.370000  0 days 00:40:00.073000    0

 [5 rows x 55 columns],
 None)

In [31]:
# Data Merge
# 5. position
race_position_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3607720 entries, 0 to 3607719
Data columns (total 10 columns):
 #   Column       Dtype
---  ------       -----
 0   Year         int64
 1   DriverName   object
 2   Date         object
 3   Status       object
 4   X            int64
 5   Y            int64
 6   Z            int64
 7   Source       object
 8   Time         object
 9   SessionTime  object
dtypes: int64(4), object(6)
memory usage: 275.2+ MB

In [35]:
race_position_data.head(), race_position_data.tail()

(   Year DriverName                     Date    Status  X  Y  Z Source  \
 0  2018        VER  2018-10-28 18:40:01.328  OffTrack  0  0  0    pos
 1  2018        VER  2018-10-28 18:40:01.628  OffTrack  0  0  0    pos
 2  2018        VER  2018-10-28 18:40:01.928  OffTrack  0  0  0    pos
 3  2018        VER  2018-10-28 18:40:02.228  OffTrack  0  0  0    pos
 4  2018        VER  2018-10-28 18:40:02.528  OffTrack  0  0  0    pos

                      Time             SessionTime
 0  0 days 00:00:01.226000  0 days 00:00:01.226000
 1  0 days 00:00:01.526000  0 days 00:00:01.526000
 2  0 days 00:00:01.826000  0 days 00:00:01.826000
 3  0 days 00:00:02.126000  0 days 00:00:02.126000
 4  0 days 00:00:02.426000  0 days 00:00:02.426000  ,
          Year DriverName                     Date   Status    X    Y      Z  \
 3607715  2023        PER  2023-10-29 22:10:44.652  OnTrack  198  944  22266
 3607716  2023        PER  2023-10-29 22:10:44.812  OnTrack  198  944  22266
 3607717  2023        PER  2023-10-29 22:10:45.132  OnTrack  198  944  22266
 3607718  2023        PER  2023-10-29 22:10:45.311  OnTrack  198  944  22266
 3607719  2023        PER  2023-10-29 22:10:45.511  OnTrack  198  944  22266

         Source                    Time             SessionTime
 3607715    pos  0 days 03:09:44.571000  0 days 03:09:44.571000
 3607716    pos  0 days 03:09:44.731000  0 days 03:09:44.731000
 3607717    pos  0 days 03:09:45.051000  0 days 03:09:45.051000
 3607718    pos  0 days 03:09:45.230000  0 days 03:09:45.230000
 3607719    pos  0 days 03:09:45.430000  0 days 03:09:45.430000  )

In [37]:
race_position_data.rename(columns={'DriverName': 'Driver'}, inplace=True)

In [39]:
# position_data
# Extract days and hours
race_position_data['Days'] = race_position_data['Time'].apply(lambda x: int(x.split(' ')[0]))
race_position_data['Hours'] = race_position_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[0]))
race_position_data['Minutes'] = race_position_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[1]))

# View the updated DataFrame
print(race_position_data)

         Year Driver                     Date    Status    X    Y      Z  \
0        2018    VER  2018-10-28 18:40:01.328  OffTrack    0    0      0
1        2018    VER  2018-10-28 18:40:01.628  OffTrack    0    0      0
2        2018    VER  2018-10-28 18:40:01.928  OffTrack    0    0      0
3        2018    VER  2018-10-28 18:40:02.228  OffTrack    0    0      0
4        2018    VER  2018-10-28 18:40:02.528  OffTrack    0    0      0
...       ...    ...                      ...       ...  ...  ...    ...
3607715  2023    PER  2023-10-29 22:10:44.652   OnTrack  198  944  22266
3607716  2023    PER  2023-10-29 22:10:44.812   OnTrack  198  944  22266
3607717  2023    PER  2023-10-29 22:10:45.132   OnTrack  198  944  22266
3607718  2023    PER  2023-10-29 22:10:45.311   OnTrack  198  944  22266
3607719  2023    PER  2023-10-29 22:10:45.511   OnTrack  198  944  22266

        Source                    Time             SessionTime  Days  Hours  \
0          pos  0 days 00:00:01.226000  0 days 00:00:01.226000     0      0
1          pos  0 days 00:00:01.526000  0 days 00:00:01.526000     0      0
2          pos  0 days 00:00:01.826000  0 days 00:00:01.826000     0      0
3          pos  0 days 00:00:02.126000  0 days 00:00:02.126000     0      0
4          pos  0 days 00:00:02.426000  0 days 00:00:02.426000     0      0
...        ...                     ...                     ...   ...    ...
3607715    pos  0 days 03:09:44.571000  0 days 03:09:44.571000     0      3
3607716    pos  0 days 03:09:44.731000  0 days 03:09:44.731000     0      3
3607717    pos  0 days 03:09:45.051000  0 days 03:09:45.051000     0      3
3607718    pos  0 days 03:09:45.230000  0 days 03:09:45.230000     0      3
3607719    pos  0 days 03:09:45.430000  0 days 03:09:45.430000     0      3

         Minutes
0              0
1              0
2              0
3              0
4              0
...          ...
3607715        9
3607716        9
3607717        9
3607718        9
3607719        9

[3607720 rows x 13 columns]

In [41]:
# Remove duplicates in position_data based on 'eventname' and 'hours'
race_position_data1 = race_position_data.drop_duplicates(subset=['Year', 'Driver', 'Hours', 'Minutes'])

# Now perform the left join
race_lap_data3 = pd.merge(race_lap_data2, race_position_data1, on=['Year', 'Driver', 'Hours', 'Minutes'], how='left', suffixes=('_left', '_right'))

# The number of rows in merged_df should now match df1

print(race_lap_data3)

      Year                  Time_x Driver  DriverNumber  \
0     2018  0 days 00:34:35.418000    GAS            10
1     2018  0 days 00:36:01.984000    GAS            10
2     2018  0 days 00:37:26.860000    GAS            10
3     2018  0 days 00:38:54.567000    GAS            10
4     2018  0 days 00:40:38.975000    GAS            10
...    ...                     ...    ...           ...
6532  2023  0 days 02:59:59.540000    PIA            81
6533  2023  0 days 03:01:22.902000    PIA            81
6534  2023  0 days 03:02:46.070000    PIA            81
6535  2023  0 days 03:04:09.050000    PIA            81
6536  2023  0 days 03:05:32.471000    PIA            81

                     LapTime  LapNumber  Stint PitOutTime  \
0     0 days 00:01:36.516000        1.0    1.0        NaN
1     0 days 00:01:26.566000        2.0    1.0        NaN
2     0 days 00:01:24.876000        3.0    1.0        NaN
3     0 days 00:01:27.707000        4.0    1.0        NaN
4     0 days 00:01:44.408000        5.0    1.0        NaN
...                      ...        ...    ...        ...
6532  0 days 00:01:23.238000       67.0    3.0        NaN
6533  0 days 00:01:23.362000       68.0    3.0        NaN
6534  0 days 00:01:23.168000       69.0    3.0        NaN
6535  0 days 00:01:22.980000       70.0    3.0        NaN
6536  0 days 00:01:23.421000       71.0    3.0        NaN

                   PitInTime             Sector1Time  ... Days_left  \
0                        NaN                     NaN  ...         0
1                        NaN  0 days 00:00:29.676000  ...         0
2                        NaN  0 days 00:00:29.359000  ...         0
3                        NaN  0 days 00:00:30.540000  ...         0
4     0 days 00:40:36.342000  0 days 00:00:41.052000  ...         0
...                      ...                     ...  ...       ...
6532                     NaN  0 days 00:00:29.080000  ...         0
6533                     NaN  0 days 00:00:29.140000  ...         0
6534                     NaN  0 days 00:00:29.060000  ...         0
6535                     NaN  0 days 00:00:29.112000  ...         0
6536                     NaN  0 days 00:00:29.165000  ...         0

                   Date_right   Status      X     Y      Z  Source_right  \
0     2018-10-28 19:14:00.358  OnTrack   7158 -4422  22270           pos
1     2018-10-28 19:16:00.359  OnTrack  -1600  1260  22264           pos
2     2018-10-28 19:17:00.360  OnTrack   5034 -3379  22271           pos
3     2018-10-28 19:18:00.362  OnTrack   8836 -7592  22281           pos
4     2018-10-28 19:20:00.363  OnTrack   7360 -4751  22270           pos
...                       ...      ...    ...   ...    ...           ...
6532  2023-10-29 22:00:00.492  OnTrack  11380 -3527  22268           pos
6533  2023-10-29 22:02:00.271  OnTrack   2614 -2096  22271           pos
6534  2023-10-29 22:03:00.232  OnTrack   8959 -8659  22290           pos
6535  2023-10-29 22:05:00.252  OnTrack  -1619  -144  22271           pos
6536  2023-10-29 22:06:00.212  OnTrack   7164 -4503  22270           pos

                  Time_right       SessionTime_right Days_right
0     0 days 00:34:00.256000  0 days 00:34:00.256000          0
1     0 days 00:36:00.257000  0 days 00:36:00.257000          0
2     0 days 00:37:00.258000  0 days 00:37:00.258000          0
3     0 days 00:38:00.260000  0 days 00:38:00.260000          0
4     0 days 00:40:00.261000  0 days 00:40:00.261000          0
...                      ...                     ...        ...
6532  0 days 02:59:00.411000  0 days 02:59:00.411000          0
6533  0 days 03:01:00.190000  0 days 03:01:00.190000          0
6534  0 days 03:02:00.151000  0 days 03:02:00.151000          0
6535  0 days 03:04:00.171000  0 days 03:04:00.171000          0
6536  0 days 03:05:00.131000  0 days 03:05:00.131000          0

[6537 rows x 64 columns]

In [43]:
race_lap_data3.head(), race_lap_data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6537 entries, 0 to 6536
Data columns (total 64 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year                6537 non-null   int64
 1   Time_x              6537 non-null   object
 2   Driver              6537 non-null   object
 3   DriverNumber        6537 non-null   int64
 4   LapTime             6500 non-null   object
 5   LapNumber           6537 non-null   float64
 6   Stint               6537 non-null   float64
 7   PitOutTime          143 non-null    object
 8   PitInTime           150 non-null    object
 9   Sector1Time         6411 non-null   object
 10  Sector2Time         6528 non-null   object
 11  Sector3Time         6527 non-null   object
 12  Sector1SessionTime  6397 non-null   object
 13  Sector2SessionTime  6528 non-null   object
 14  Sector3SessionTime  6527 non-null   object
 15  SpeedI1             5941 non-null   float64
 16  SpeedI2             6527 non-null   float64
 17  SpeedFL             6380 non-null   float64
 18  SpeedST             5375 non-null   float64
 19  IsPersonalBest      6532 non-null   object
 20  Compound            6537 non-null   object
 21  TyreLife            6537 non-null   float64
 22  FreshTyre           6537 non-null   bool
 23  Team                6537 non-null   object
 24  LapStartTime        6537 non-null   object
 25  LapStartDate        6532 non-null   object
 26  TrackStatus         6537 non-null   int64
 27  Position            6530 non-null   float64
 28  Deleted             6537 non-null   bool
 29  DeletedReason       12 non-null     object
 30  FastF1Generated     6537 non-null   bool
 31  IsAccurate          6537 non-null   bool
 32  Days_x              6537 non-null   int64
 33  Hours               6537 non-null   int64
 34  Minutes             6537 non-null   int64
 35  Time_y              6537 non-null   object
 36  AirTemp             6537 non-null   float64
 37  Humidity            6537 non-null   float64
 38  Pressure            6537 non-null   float64
 39  Rainfall            6537 non-null   bool
 40  TrackTemp           6537 non-null   float64
 41  WindDirection       6537 non-null   int64
 42  WindSpeed           6537 non-null   float64
 43  Days_y              6537 non-null   int64
 44  Date_left           6537 non-null   object
 45  RPM                 6537 non-null   int64
 46  Speed               6537 non-null   int64
 47  nGear               6537 non-null   int64
 48  Throttle            6537 non-null   int64
 49  Brake               6537 non-null   bool
 50  DRS                 6537 non-null   int64
 51  Source_left         6537 non-null   object
 52  Time_left           6537 non-null   object
 53  SessionTime_left    6537 non-null   object
 54  Days_left           6537 non-null   int64
 55  Date_right          6537 non-null   object
 56  Status              6537 non-null   object
 57  X                   6537 non-null   int64
 58  Y                   6537 non-null   int64
 59  Z                   6537 non-null   int64
 60  Source_right        6537 non-null   object
 61  Time_right          6537 non-null   object
 62  SessionTime_right   6537 non-null   object
 63  Days_right          6537 non-null   int64
dtypes: bool(6), float64(13), int64(18), object(27)
memory usage: 2.9+ MB

(   Year                  Time_x Driver  DriverNumber                 LapTime  \
 0  2018  0 days 00:34:35.418000    GAS            10  0 days 00:01:36.516000
 1  2018  0 days 00:36:01.984000    GAS            10  0 days 00:01:26.566000
 2  2018  0 days 00:37:26.860000    GAS            10  0 days 00:01:24.876000
 3  2018  0 days 00:38:54.567000    GAS            10  0 days 00:01:27.707000
 4  2018  0 days 00:40:38.975000    GAS            10  0 days 00:01:44.408000

    LapNumber  Stint PitOutTime               PitInTime  \
 0        1.0    1.0        NaN                     NaN
 1        2.0    1.0        NaN                     NaN
 2        3.0    1.0        NaN                     NaN
 3        4.0    1.0        NaN                     NaN
 4        5.0    1.0        NaN  0 days 00:40:36.342000

               Sector1Time  ... Days_left               Date_right   Status  \
 0                     NaN  ...         0  2018-10-28 19:14:00.358  OnTrack
 1  0 days 00:00:29.676000  ...         0  2018-10-28 19:16:00.359  OnTrack
 2  0 days 00:00:29.359000  ...         0  2018-10-28 19:17:00.360  OnTrack
 3  0 days 00:00:30.540000  ...         0  2018-10-28 19:18:00.362  OnTrack
 4  0 days 00:00:41.052000  ...         0  2018-10-28 19:20:00.363  OnTrack

       X     Y      Z  Source_right              Time_right  \
 0  7158 -4422  22270           pos  0 days 00:34:00.256000
 1 -1600  1260  22264           pos  0 days 00:36:00.257000
 2  5034 -3379  22271           pos  0 days 00:37:00.258000
 3  8836 -7592  22281           pos  0 days 00:38:00.260000
 4  7360 -4751  22270           pos  0 days 00:40:00.261000

         SessionTime_right Days_right
 0  0 days 00:34:00.256000          0
 1  0 days 00:36:00.257000          0
 2  0 days 00:37:00.258000          0
 3  0 days 00:38:00.260000          0
 4  0 days 00:40:00.261000          0

 [5 rows x 64 columns],
 None)

In [ ]:
# Data Merge
# 6. result_data

In [45]:
race_result_data.info(), race_result_data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year                100 non-null    int64
 1   DriverNumber        100 non-null    int64
 2   BroadcastName       100 non-null    object
 3   Abbreviation        100 non-null    object
 4   DriverId            100 non-null    object
 5   TeamName            100 non-null    object
 6   TeamColor           100 non-null    object
 7   TeamId              100 non-null    object
 8   FirstName           100 non-null    object
 9   LastName            100 non-null    object
 10  FullName            100 non-null    object
 11  HeadshotUrl         78 non-null     object
 12  CountryCode         40 non-null     object
 13  Position            100 non-null    float64
 14  ClassifiedPosition  100 non-null    object
 15  GridPosition        100 non-null    float64
 16  Q1                  0 non-null      float64
 17  Q2                  0 non-null      float64
 18  Q3                  0 non-null      float64
 19  Time                38 non-null     object
 20  Status              100 non-null    object
 21  Points              100 non-null    float64
dtypes: float64(6), int64(2), object(14)
memory usage: 17.3+ KB

(None,
    Year  DriverNumber BroadcastName Abbreviation        DriverId  \
 0  2018            33  M VERSTAPPEN          VER  max_verstappen
 1  2018             5      S VETTEL          VET          vettel
 2  2018             7   K RAIKKONEN          RAI       raikkonen
 3  2018            44    L HAMILTON          HAM        hamilton
 4  2018            77      V BOTTAS          BOT          bottas

           TeamName TeamColor    TeamId  FirstName    LastName  ...  \
 0  Red Bull Racing    1E41FF  red_bull        Max  Verstappen  ...
 1          Ferrari    DC0000   ferrari  Sebastian      Vettel  ...
 2          Ferrari    DC0000   ferrari       Kimi   Räikkönen  ...
 3         Mercedes    00D2BE  mercedes      Lewis    Hamilton  ...
 4         Mercedes    00D2BE  mercedes   Valtteri      Bottas  ...

   CountryCode Position ClassifiedPosition  GridPosition  Q1  Q2  Q3  \
 0         NaN      1.0                  1           2.0 NaN NaN NaN
 1         NaN      2.0                  2           4.0 NaN NaN NaN
 2         NaN      3.0                  3           6.0 NaN NaN NaN
 3         NaN      4.0                  4           3.0 NaN NaN NaN
 4         NaN      5.0                  5           5.0 NaN NaN NaN

                      Time    Status Points
 0  0 days 01:38:28.851000  Finished   25.0
 1  0 days 00:00:17.316000  Finished   18.0
 2  0 days 00:00:49.914000  Finished   15.0
 3  0 days 00:01:18.738000  Finished   12.0
 4                     NaN    +1 Lap   10.0

 [5 rows x 22 columns])

In [47]:
race_result_data.rename(columns={'Abbreviation': 'Driver'}, inplace=True)

In [49]:
# Remove duplicates in result_data based on 'eventname' and 'hours'
# result_data1 = result_data.drop_duplicates(subset=['EventName', 'Hours', 'Minutes'])

# Now perform the left join
race_lap_data4 = pd.merge(race_lap_data3, race_result_data, on=['Year', 'Driver'], how='left', suffixes=('_left', '_right'))

# The number of rows in merged_df should now match df1

print(race_lap_data4)

      Year                  Time_x Driver  DriverNumber_left  \
0     2018  0 days 00:34:35.418000    GAS                 10
1     2018  0 days 00:36:01.984000    GAS                 10
2     2018  0 days 00:37:26.860000    GAS                 10
3     2018  0 days 00:38:54.567000    GAS                 10
4     2018  0 days 00:40:38.975000    GAS                 10
...    ...                     ...    ...                ...
6532  2023  0 days 02:59:59.540000    PIA                 81
6533  2023  0 days 03:01:22.902000    PIA                 81
6534  2023  0 days 03:02:46.070000    PIA                 81
6535  2023  0 days 03:04:09.050000    PIA                 81
6536  2023  0 days 03:05:32.471000    PIA                 81

                     LapTime  LapNumber  Stint PitOutTime  \
0     0 days 00:01:36.516000        1.0    1.0        NaN
1     0 days 00:01:26.566000        2.0    1.0        NaN
2     0 days 00:01:24.876000        3.0    1.0        NaN
3     0 days 00:01:27.707000        4.0    1.0        NaN
4     0 days 00:01:44.408000        5.0    1.0        NaN
...                      ...        ...    ...        ...
6532  0 days 00:01:23.238000       67.0    3.0        NaN
6533  0 days 00:01:23.362000       68.0    3.0        NaN
6534  0 days 00:01:23.168000       69.0    3.0        NaN
6535  0 days 00:01:22.980000       70.0    3.0        NaN
6536  0 days 00:01:23.421000       71.0    3.0        NaN

                   PitInTime             Sector1Time  ... CountryCode  \
0                        NaN                     NaN  ...         NaN
1                        NaN  0 days 00:00:29.676000  ...         NaN
2                        NaN  0 days 00:00:29.359000  ...         NaN
3                        NaN  0 days 00:00:30.540000  ...         NaN
4     0 days 00:40:36.342000  0 days 00:00:41.052000  ...         NaN
...                      ...                     ...  ...         ...
6532                     NaN  0 days 00:00:29.080000  ...         AUS
6533                     NaN  0 days 00:00:29.140000  ...         AUS
6534                     NaN  0 days 00:00:29.060000  ...         AUS
6535                     NaN  0 days 00:00:29.112000  ...         AUS
6536                     NaN  0 days 00:00:29.165000  ...         AUS

     Position_right ClassifiedPosition GridPosition  Q1  Q2  Q3  \
0              10.0                 10         20.0 NaN NaN NaN
1              10.0                 10         20.0 NaN NaN NaN
2              10.0                 10         20.0 NaN NaN NaN
3              10.0                 10         20.0 NaN NaN NaN
4              10.0                 10         20.0 NaN NaN NaN
...             ...                ...          ...  ..  ..  ..
6532            8.0                  8          7.0 NaN NaN NaN
6533            8.0                  8          7.0 NaN NaN NaN
6534            8.0                  8          7.0 NaN NaN NaN
6535            8.0                  8          7.0 NaN NaN NaN
6536            8.0                  8          7.0 NaN NaN NaN

                        Time  Status_right Points
0                        NaN       +2 Laps    1.0
1                        NaN       +2 Laps    1.0
2                        NaN       +2 Laps    1.0
3                        NaN       +2 Laps    1.0
4                        NaN       +2 Laps    1.0
...                      ...           ...    ...
6532  0 days 00:00:43.104000      Finished    4.0
6533  0 days 00:00:43.104000      Finished    4.0
6534  0 days 00:00:43.104000      Finished    4.0
6535  0 days 00:00:43.104000      Finished    4.0
6536  0 days 00:00:43.104000      Finished    4.0

[6537 rows x 84 columns]

In [51]:
race_lap_data4.info(), race_lap_data4.describe(), race_lap_data4.describe(include='object')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6537 entries, 0 to 6536
Data columns (total 84 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year                6537 non-null   int64
 1   Time_x              6537 non-null   object
 2   Driver              6537 non-null   object
 3   DriverNumber_left   6537 non-null   int64
 4   LapTime             6500 non-null   object
 5   LapNumber           6537 non-null   float64
 6   Stint               6537 non-null   float64
 7   PitOutTime          143 non-null    object
 8   PitInTime           150 non-null    object
 9   Sector1Time         6411 non-null   object
 10  Sector2Time         6528 non-null   object
 11  Sector3Time         6527 non-null   object
 12  Sector1SessionTime  6397 non-null   object
 13  Sector2SessionTime  6528 non-null   object
 14  Sector3SessionTime  6527 non-null   object
 15  SpeedI1             5941 non-null   float64
 16  SpeedI2             6527 non-null   float64
 17  SpeedFL             6380 non-null   float64
 18  SpeedST             5375 non-null   float64
 19  IsPersonalBest      6532 non-null   object
 20  Compound            6537 non-null   object
 21  TyreLife            6537 non-null   float64
 22  FreshTyre           6537 non-null   bool
 23  Team                6537 non-null   object
 24  LapStartTime        6537 non-null   object
 25  LapStartDate        6532 non-null   object
 26  TrackStatus         6537 non-null   int64
 27  Position_left       6530 non-null   float64
 28  Deleted             6537 non-null   bool
 29  DeletedReason       12 non-null     object
 30  FastF1Generated     6537 non-null   bool
 31  IsAccurate          6537 non-null   bool
 32  Days_x              6537 non-null   int64
 33  Hours               6537 non-null   int64
 34  Minutes             6537 non-null   int64
 35  Time_y              6537 non-null   object
 36  AirTemp             6537 non-null   float64
 37  Humidity            6537 non-null   float64
 38  Pressure            6537 non-null   float64
 39  Rainfall            6537 non-null   bool
 40  TrackTemp           6537 non-null   float64
 41  WindDirection       6537 non-null   int64
 42  WindSpeed           6537 non-null   float64
 43  Days_y              6537 non-null   int64
 44  Date_left           6537 non-null   object
 45  RPM                 6537 non-null   int64
 46  Speed               6537 non-null   int64
 47  nGear               6537 non-null   int64
 48  Throttle            6537 non-null   int64
 49  Brake               6537 non-null   bool
 50  DRS                 6537 non-null   int64
 51  Source_left         6537 non-null   object
 52  Time_left           6537 non-null   object
 53  SessionTime_left    6537 non-null   object
 54  Days_left           6537 non-null   int64
 55  Date_right          6537 non-null   object
 56  Status_left         6537 non-null   object
 57  X                   6537 non-null   int64
 58  Y                   6537 non-null   int64
 59  Z                   6537 non-null   int64
 60  Source_right        6537 non-null   object
 61  Time_right          6537 non-null   object
 62  SessionTime_right   6537 non-null   object
 63  Days_right          6537 non-null   int64
 64  DriverNumber_right  6537 non-null   int64
 65  BroadcastName       6537 non-null   object
 66  DriverId            6537 non-null   object
 67  TeamName            6537 non-null   object
 68  TeamColor           6537 non-null   object
 69  TeamId              6537 non-null   object
 70  FirstName           6537 non-null   object
 71  LastName            6537 non-null   object
 72  FullName            6537 non-null   object
 73  HeadshotUrl         5151 non-null   object
 74  CountryCode         2661 non-null   object
 75  Position_right      6537 non-null   float64
 76  ClassifiedPosition  6537 non-null   object
 77  GridPosition        6537 non-null   float64
 78  Q1                  0 non-null      float64
 79  Q2                  0 non-null      float64
 80  Q3                  0 non-null      float64
 81  Time                2698 non-null   object
 82  Status_right        6537 non-null   object
 83  Points              6537 non-null   float64
dtypes: bool(6), float64(19), int64(19), object(40)
memory usage: 3.9+ MB

(None,
               Year  DriverNumber_left    LapNumber        Stint      SpeedI1  \
 count  6537.000000        6537.000000  6537.000000  6537.000000  5941.000000
 mean   2020.612666          27.361787    34.897048     1.845801   281.768221
 std       1.843447          24.730164    20.170038     0.744479    23.316559
 min    2018.000000           1.000000     1.000000     1.000000    80.000000
 25%    2019.000000           8.000000    17.000000     1.000000   279.000000
 50%    2021.000000          20.000000    35.000000     2.000000   287.000000
 75%    2022.000000          44.000000    52.000000     2.000000   293.000000
 max    2023.000000          99.000000    71.000000     5.000000   316.000000

            SpeedI2      SpeedFL      SpeedST     TyreLife  TrackStatus  ...  \
 count  6527.000000  6380.000000  5375.000000  6537.000000  6537.000000  ...
 mean    278.259231   244.110502   324.037023    18.776044    17.895977  ...
 std      21.404763    18.018459    27.306969    12.280522   148.628165  ...
 min      77.000000    33.000000    93.000000     1.000000     1.000000  ...
 25%     279.000000   244.000000   323.000000     9.000000     1.000000  ...
 50%     282.000000   247.000000   327.000000    17.000000     1.000000  ...
 75%     285.000000   249.000000   333.000000    27.000000     1.000000  ...
 max     300.000000   260.000000   364.000000    66.000000  2671.000000  ...

                   Y             Z  Days_right  DriverNumber_right  \
 count   6537.000000   6537.000000      6537.0         6537.000000
 mean   -3866.128958  22273.995564         0.0           27.361787
 std     3322.848977      7.293242         0.0           24.730164
 min   -12975.000000  22263.000000         0.0            1.000000
 25%    -7178.000000  22270.000000         0.0            8.000000
 50%    -3886.000000  22271.000000         0.0           20.000000
 75%     -451.000000  22278.000000         0.0           44.000000
 max     1297.000000  22291.000000         0.0           99.000000

        Position_right  GridPosition   Q1   Q2   Q3       Points
 count     6537.000000   6537.000000  0.0  0.0  0.0  6537.000000
 mean         9.810464     10.160777  NaN  NaN  NaN     5.503901
 std          5.432322      5.862355  NaN  NaN  NaN     7.359165
 min          1.000000      0.000000  NaN  NaN  NaN     0.000000
 25%          5.000000      5.000000  NaN  NaN  NaN     0.000000
 50%         10.000000     10.000000  NaN  NaN  NaN     1.000000
 75%         14.000000     15.000000  NaN  NaN  NaN    10.000000
 max         20.000000     20.000000  NaN  NaN  NaN    25.000000

 [8 rows x 38 columns],
                         Time_x Driver                 LapTime  \
 count                     6537   6537                    6500
 unique                    6532     33                    4369
 top     0 days 01:03:48.427000    VER  0 days 00:01:25.057000
 freq                         3    355                       6

                     PitOutTime               PitInTime  \
 count                      143                     150
 unique                     143                     150
 top     0 days 00:40:58.947000  0 days 00:40:36.342000
 freq                         1                       1

                    Sector1Time             Sector2Time  \
 count                     6411                    6528
 unique                    2144                    3153
 top     0 days 00:00:29.213000  0 days 00:00:32.739000
 freq                        13                       9

                    Sector3Time      Sector1SessionTime  \
 count                     6527                    6397
 unique                    2260                    6397
 top     0 days 00:00:21.574000  0 days 00:35:05.078000
 freq                        12                       1

             Sector2SessionTime  ... TeamColor   TeamId FirstName    LastName  \
 count                     6528  ...      6537     6537      6537        6537
 unique                    6527  ...        47       15        33          33
 top     0 days 01:03:26.440000  ...    00D2BE  ferrari       Max  Verstappen
 freq                         2  ...       281      709       355         355

               FullName                                        HeadshotUrl  \
 count             6537                                               5151
 unique              33                                                 46
 top     Max Verstappen  https://www.formula1.com/content/dam/fom-websi...
 freq               355                                                213

        CountryCode ClassifiedPosition                    Time Status_right
 count         2661               6537                    2698         6537
 unique          15                 20                      38           13
 top            GBR                  R  0 days 01:38:28.851000     Finished
 freq           425                371                      71         2698

 [4 rows x 40 columns])

In [53]:
race_lap_data4['Date_left']

0       2018-10-28 19:14:00.290
1       2018-10-28 19:16:00.212
2       2018-10-28 19:17:00.293
3       2018-10-28 19:18:00.133
4       2018-10-28 19:20:00.175
                 ...
6532    2023-10-29 22:00:00.233
6533    2023-10-29 22:02:00.354
6534    2023-10-29 22:03:00.234
6535    2023-10-29 22:05:00.274
6536    2023-10-29 22:06:00.234
Name: Date_left, Length: 6537, dtype: object

In [55]:
race_lap_data4['Date_right']

0       2018-10-28 19:14:00.358
1       2018-10-28 19:16:00.359
2       2018-10-28 19:17:00.360
3       2018-10-28 19:18:00.362
4       2018-10-28 19:20:00.363
                 ...
6532    2023-10-29 22:00:00.492
6533    2023-10-29 22:02:00.271
6534    2023-10-29 22:03:00.232
6535    2023-10-29 22:05:00.252
6536    2023-10-29 22:06:00.212
Name: Date_right, Length: 6537, dtype: object

In [ ]:
# Data Merge
# 3. control_message (Cancelled due to similar data from track_status)
# print(control_message_data)

In [57]:
# Data Merge
# 7. track_status
print(race_track_status_data)

    Year                    Time  Status      Message
0   2018  0 days 00:05:20.880000       1     AllClear
1   2018  0 days 00:38:30.932000       2       Yellow
2   2018  0 days 00:38:48.936000       1     AllClear
3   2018  0 days 00:38:53.651000       2       Yellow
4   2018  0 days 00:38:58.567000       6  VSCDeployed
5   2018  0 days 00:39:55.469000       7    VSCEnding
6   2018  0 days 00:40:06.874000       1     AllClear
7   2018  0 days 01:14:15.429000       2       Yellow
8   2018  0 days 01:14:41.480000       6  VSCDeployed
9   2018  0 days 01:17:37.957000       7    VSCEnding
10  2018  0 days 01:17:50.261000       1     AllClear
11  2018  0 days 01:57:58.372000       2       Yellow
12  2018  0 days 01:58:13.123000       6  VSCDeployed
13  2018  0 days 02:00:43.030000       7    VSCEnding
14  2018  0 days 02:00:57.466000       1     AllClear
15  2019         0 days 00:00:00       1     AllClear
16  2019  0 days 00:34:13.665000       6  VSCDeployed
17  2019  0 days 00:36:25.134000       7    VSCEnding
18  2019  0 days 00:36:44.204000       1     AllClear
19  2019  0 days 00:40:12.845000       2       Yellow
20  2019  0 days 00:40:29.452000       1     AllClear
21  2019  0 days 02:10:07.154000       2       Yellow
22  2019  0 days 02:10:11.735000       1     AllClear
23  2021         0 days 00:00:00       2       Yellow
24  2021  0 days 00:07:05.555000       1     AllClear
25  2021  0 days 01:02:25.133000       2       Yellow
26  2021  0 days 01:03:02.255000       4   SCDeployed
27  2021  0 days 01:10:07.807000       1     AllClear
28  2022  0 days 00:00:02.936000       2       Yellow
29  2022  0 days 00:06:31.711000       1     AllClear
30  2022  0 days 02:31:34.690000       2       Yellow
31  2022  0 days 02:31:57.090000       6  VSCDeployed
32  2022  0 days 02:32:50.946000       7    VSCEnding
33  2022  0 days 02:33:02.399000       1     AllClear
34  2023         0 days 00:00:00       2       Yellow
35  2023  0 days 00:07:53.470000       1     AllClear
36  2023  0 days 00:21:05.410000       2       Yellow
37  2023  0 days 00:35:24.238000       1     AllClear
38  2023  0 days 01:02:36.381000       2       Yellow
39  2023  0 days 01:02:47.162000       1     AllClear
40  2023  0 days 01:08:04.985000       6  VSCDeployed
41  2023  0 days 01:09:21.515000       7    VSCEnding
42  2023  0 days 01:09:34.046000       1     AllClear
43  2023  0 days 01:13:02.902000       2       Yellow
44  2023  0 days 01:13:03.933000       1     AllClear
45  2023  0 days 01:48:03.943000       2       Yellow
46  2023  0 days 01:48:23.927000       4   SCDeployed
47  2023  0 days 01:50:53.065000       5          Red
48  2023  0 days 02:06:42.923000       1     AllClear
49  2023  0 days 02:12:19.214000       4   SCDeployed
50  2023  0 days 02:13:48.634000       1     AllClear
51  2023  0 days 02:33:53.613000       2       Yellow
52  2023  0 days 02:34:08.394000       1     AllClear
53  2023  0 days 02:58:56.009000       2       Yellow
54  2023  0 days 02:59:07.259000       1     AllClear

In [59]:
race_track_status_data.head(20)

    Year                    Time  Status      Message
0   2018  0 days 00:05:20.880000       1     AllClear
1   2018  0 days 00:38:30.932000       2       Yellow
2   2018  0 days 00:38:48.936000       1     AllClear
3   2018  0 days 00:38:53.651000       2       Yellow
4   2018  0 days 00:38:58.567000       6  VSCDeployed
5   2018  0 days 00:39:55.469000       7    VSCEnding
6   2018  0 days 00:40:06.874000       1     AllClear
7   2018  0 days 01:14:15.429000       2       Yellow
8   2018  0 days 01:14:41.480000       6  VSCDeployed
9   2018  0 days 01:17:37.957000       7    VSCEnding
10  2018  0 days 01:17:50.261000       1     AllClear
11  2018  0 days 01:57:58.372000       2       Yellow
12  2018  0 days 01:58:13.123000       6  VSCDeployed
13  2018  0 days 02:00:43.030000       7    VSCEnding
14  2018  0 days 02:00:57.466000       1     AllClear
15  2019         0 days 00:00:00       1     AllClear
16  2019  0 days 00:34:13.665000       6  VSCDeployed
17  2019  0 days 00:36:25.134000       7    VSCEnding
18  2019  0 days 00:36:44.204000       1     AllClear
19  2019  0 days 00:40:12.845000       2       Yellow

In [61]:
# track_status_data
# Extract days and hours
race_track_status_data['Days'] = race_track_status_data['Time'].apply(lambda x: int(x.split(' ')[0]))
race_track_status_data['Hours'] = race_track_status_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[0]))
race_track_status_data['Minutes'] = race_track_status_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[1]))

# View the updated DataFrame
print(race_track_status_data)

    Year                    Time  Status      Message  Days  Hours  Minutes
0   2018  0 days 00:05:20.880000       1     AllClear     0      0        5
1   2018  0 days 00:38:30.932000       2       Yellow     0      0       38
2   2018  0 days 00:38:48.936000       1     AllClear     0      0       38
3   2018  0 days 00:38:53.651000       2       Yellow     0      0       38
4   2018  0 days 00:38:58.567000       6  VSCDeployed     0      0       38
5   2018  0 days 00:39:55.469000       7    VSCEnding     0      0       39
6   2018  0 days 00:40:06.874000       1     AllClear     0      0       40
7   2018  0 days 01:14:15.429000       2       Yellow     0      1       14
8   2018  0 days 01:14:41.480000       6  VSCDeployed     0      1       14
9   2018  0 days 01:17:37.957000       7    VSCEnding     0      1       17
10  2018  0 days 01:17:50.261000       1     AllClear     0      1       17
11  2018  0 days 01:57:58.372000       2       Yellow     0      1       57
12  2018  0 days 01:58:13.123000       6  VSCDeployed     0      1       58
13  2018  0 days 02:00:43.030000       7    VSCEnding     0      2        0
14  2018  0 days 02:00:57.466000       1     AllClear     0      2        0
15  2019         0 days 00:00:00       1     AllClear     0      0        0
16  2019  0 days 00:34:13.665000       6  VSCDeployed     0      0       34
17  2019  0 days 00:36:25.134000       7    VSCEnding     0      0       36
18  2019  0 days 00:36:44.204000       1     AllClear     0      0       36
19  2019  0 days 00:40:12.845000       2       Yellow     0      0       40
20  2019  0 days 00:40:29.452000       1     AllClear     0      0       40
21  2019  0 days 02:10:07.154000       2       Yellow     0      2       10
22  2019  0 days 02:10:11.735000       1     AllClear     0      2       10
23  2021         0 days 00:00:00       2       Yellow     0      0        0
24  2021  0 days 00:07:05.555000       1     AllClear     0      0        7
25  2021  0 days 01:02:25.133000       2       Yellow     0      1        2
26  2021  0 days 01:03:02.255000       4   SCDeployed     0      1        3
27  2021  0 days 01:10:07.807000       1     AllClear     0      1       10
28  2022  0 days 00:00:02.936000       2       Yellow     0      0        0
29  2022  0 days 00:06:31.711000       1     AllClear     0      0        6
30  2022  0 days 02:31:34.690000       2       Yellow     0      2       31
31  2022  0 days 02:31:57.090000       6  VSCDeployed     0      2       31
32  2022  0 days 02:32:50.946000       7    VSCEnding     0      2       32
33  2022  0 days 02:33:02.399000       1     AllClear     0      2       33
34  2023         0 days 00:00:00       2       Yellow     0      0        0
35  2023  0 days 00:07:53.470000       1     AllClear     0      0        7
36  2023  0 days 00:21:05.410000       2       Yellow     0      0       21
37  2023  0 days 00:35:24.238000       1     AllClear     0      0       35
38  2023  0 days 01:02:36.381000       2       Yellow     0      1        2
39  2023  0 days 01:02:47.162000       1     AllClear     0      1        2
40  2023  0 days 01:08:04.985000       6  VSCDeployed     0      1        8
41  2023  0 days 01:09:21.515000       7    VSCEnding     0      1        9
42  2023  0 days 01:09:34.046000       1     AllClear     0      1        9
43  2023  0 days 01:13:02.902000       2       Yellow     0      1       13
44  2023  0 days 01:13:03.933000       1     AllClear     0      1       13
45  2023  0 days 01:48:03.943000       2       Yellow     0      1       48
46  2023  0 days 01:48:23.927000       4   SCDeployed     0      1       48
47  2023  0 days 01:50:53.065000       5          Red     0      1       50
48  2023  0 days 02:06:42.923000       1     AllClear     0      2        6
49  2023  0 days 02:12:19.214000       4   SCDeployed     0      2       12
50  2023  0 days 02:13:48.634000       1     AllClear     0      2       13
51  2023  0 days 02:33:53.613000       2       Yellow     0      2       33
52  2023  0 days 02:34:08.394000       1     AllClear     0      2       34
53  2023  0 days 02:58:56.009000       2       Yellow     0      2       58
54  2023  0 days 02:59:07.259000       1     AllClear     0      2       59

In [63]:
# Remove duplicates in track_status_data based on 'eventname' and 'hours'
race_track_status_data1 = race_track_status_data.drop_duplicates(subset=['Year', 'Hours', 'Minutes'])

# Now perform the left join
race_lap_data5 = pd.merge(race_lap_data4, race_track_status_data1, on=['Year', 'Hours', 'Minutes'], how='left', suffixes=('_left2', '_right2'))

# The number of rows in merged_df should now match df1

print(race_lap_data5)

      Year                  Time_x Driver  DriverNumber_left  \
0     2018  0 days 00:34:35.418000    GAS                 10
1     2018  0 days 00:36:01.984000    GAS                 10
2     2018  0 days 00:37:26.860000    GAS                 10
3     2018  0 days 00:38:54.567000    GAS                 10
4     2018  0 days 00:40:38.975000    GAS                 10
...    ...                     ...    ...                ...
6532  2023  0 days 02:59:59.540000    PIA                 81
6533  2023  0 days 03:01:22.902000    PIA                 81
6534  2023  0 days 03:02:46.070000    PIA                 81
6535  2023  0 days 03:04:09.050000    PIA                 81
6536  2023  0 days 03:05:32.471000    PIA                 81

                     LapTime  LapNumber  Stint PitOutTime  \
0     0 days 00:01:36.516000        1.0    1.0        NaN
1     0 days 00:01:26.566000        2.0    1.0        NaN
2     0 days 00:01:24.876000        3.0    1.0        NaN
3     0 days 00:01:27.707000        4.0    1.0        NaN
4     0 days 00:01:44.408000        5.0    1.0        NaN
...                      ...        ...    ...        ...
6532  0 days 00:01:23.238000       67.0    3.0        NaN
6533  0 days 00:01:23.362000       68.0    3.0        NaN
6534  0 days 00:01:23.168000       69.0    3.0        NaN
6535  0 days 00:01:22.980000       70.0    3.0        NaN
6536  0 days 00:01:23.421000       71.0    3.0        NaN

                   PitInTime             Sector1Time  ...  Q1  Q2  Q3  \
0                        NaN                     NaN  ... NaN NaN NaN
1                        NaN  0 days 00:00:29.676000  ... NaN NaN NaN
2                        NaN  0 days 00:00:29.359000  ... NaN NaN NaN
3                        NaN  0 days 00:00:30.540000  ... NaN NaN NaN
4     0 days 00:40:36.342000  0 days 00:00:41.052000  ... NaN NaN NaN
...                      ...                     ...  ...  ..  ..  ..
6532                     NaN  0 days 00:00:29.080000  ... NaN NaN NaN
6533                     NaN  0 days 00:00:29.140000  ... NaN NaN NaN
6534                     NaN  0 days 00:00:29.060000  ... NaN NaN NaN
6535                     NaN  0 days 00:00:29.112000  ... NaN NaN NaN
6536                     NaN  0 days 00:00:29.165000  ... NaN NaN NaN

                  Time_left2 Status_right  Points             Time_right2  \
0                        NaN      +2 Laps     1.0                     NaN
1                        NaN      +2 Laps     1.0                     NaN
2                        NaN      +2 Laps     1.0                     NaN
3                        NaN      +2 Laps     1.0  0 days 00:38:30.932000
4                        NaN      +2 Laps     1.0  0 days 00:40:06.874000
...                      ...          ...     ...                     ...
6532  0 days 00:00:43.104000     Finished     4.0  0 days 02:59:07.259000
6533  0 days 00:00:43.104000     Finished     4.0                     NaN
6534  0 days 00:00:43.104000     Finished     4.0                     NaN
6535  0 days 00:00:43.104000     Finished     4.0                     NaN
6536  0 days 00:00:43.104000     Finished     4.0                     NaN

      Status   Message Days
0        NaN       NaN  NaN
1        NaN       NaN  NaN
2        NaN       NaN  NaN
3        2.0    Yellow  0.0
4        1.0  AllClear  0.0
...      ...       ...  ...
6532     1.0  AllClear  0.0
6533     NaN       NaN  NaN
6534     NaN       NaN  NaN
6535     NaN       NaN  NaN
6536     NaN       NaN  NaN

[6537 rows x 88 columns]

In [65]:
race_lap_data5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6537 entries, 0 to 6536
Data columns (total 88 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year                6537 non-null   int64
 1   Time_x              6537 non-null   object
 2   Driver              6537 non-null   object
 3   DriverNumber_left   6537 non-null   int64
 4   LapTime             6500 non-null   object
 5   LapNumber           6537 non-null   float64
 6   Stint               6537 non-null   float64
 7   PitOutTime          143 non-null    object
 8   PitInTime           150 non-null    object
 9   Sector1Time         6411 non-null   object
 10  Sector2Time         6528 non-null   object
 11  Sector3Time         6527 non-null   object
 12  Sector1SessionTime  6397 non-null   object
 13  Sector2SessionTime  6528 non-null   object
 14  Sector3SessionTime  6527 non-null   object
 15  SpeedI1             5941 non-null   float64
 16  SpeedI2             6527 non-null   float64
 17  SpeedFL             6380 non-null   float64
 18  SpeedST             5375 non-null   float64
 19  IsPersonalBest      6532 non-null   object
 20  Compound            6537 non-null   object
 21  TyreLife            6537 non-null   float64
 22  FreshTyre           6537 non-null   bool
 23  Team                6537 non-null   object
 24  LapStartTime        6537 non-null   object
 25  LapStartDate        6532 non-null   object
 26  TrackStatus         6537 non-null   int64
 27  Position_left       6530 non-null   float64
 28  Deleted             6537 non-null   bool
 29  DeletedReason       12 non-null     object
 30  FastF1Generated     6537 non-null   bool
 31  IsAccurate          6537 non-null   bool
 32  Days_x              6537 non-null   int64
 33  Hours               6537 non-null   int64
 34  Minutes             6537 non-null   int64
 35  Time_y              6537 non-null   object
 36  AirTemp             6537 non-null   float64
 37  Humidity            6537 non-null   float64
 38  Pressure            6537 non-null   float64
 39  Rainfall            6537 non-null   bool
 40  TrackTemp           6537 non-null   float64
 41  WindDirection       6537 non-null   int64
 42  WindSpeed           6537 non-null   float64
 43  Days_y              6537 non-null   int64
 44  Date_left           6537 non-null   object
 45  RPM                 6537 non-null   int64
 46  Speed               6537 non-null   int64
 47  nGear               6537 non-null   int64
 48  Throttle            6537 non-null   int64
 49  Brake               6537 non-null   bool
 50  DRS                 6537 non-null   int64
 51  Source_left         6537 non-null   object
 52  Time_left           6537 non-null   object
 53  SessionTime_left    6537 non-null   object
 54  Days_left           6537 non-null   int64
 55  Date_right          6537 non-null   object
 56  Status_left         6537 non-null   object
 57  X                   6537 non-null   int64
 58  Y                   6537 non-null   int64
 59  Z                   6537 non-null   int64
 60  Source_right        6537 non-null   object
 61  Time_right          6537 non-null   object
 62  SessionTime_right   6537 non-null   object
 63  Days_right          6537 non-null   int64
 64  DriverNumber_right  6537 non-null   int64
 65  BroadcastName       6537 non-null   object
 66  DriverId            6537 non-null   object
 67  TeamName            6537 non-null   object
 68  TeamColor           6537 non-null   object
 69  TeamId              6537 non-null   object
 70  FirstName           6537 non-null   object
 71  LastName            6537 non-null   object
 72  FullName            6537 non-null   object
 73  HeadshotUrl         5151 non-null   object
 74  CountryCode         2661 non-null   object
 75  Position_right      6537 non-null   float64
 76  ClassifiedPosition  6537 non-null   object
 77  GridPosition        6537 non-null   float64
 78  Q1                  0 non-null      float64
 79  Q2                  0 non-null      float64
 80  Q3                  0 non-null      float64
 81  Time_left2          2698 non-null   object
 82  Status_right        6537 non-null   object
 83  Points              6537 non-null   float64
 84  Time_right2         330 non-null    object
 85  Status              330 non-null    float64
 86  Message             330 non-null    object
 87  Days                330 non-null    float64
dtypes: bool(6), float64(21), int64(19), object(42)
memory usage: 4.1+ MB

In [67]:
# Data Merge
# 7. session_status_data
print(race_session_status_data)

    Year                    Time     Status
0   2018  0 days 00:00:05.668000   Inactive
1   2018  0 days 00:32:58.703000    Started
2   2018  0 days 02:11:27.752000   Finished
3   2018  0 days 02:17:35.869000  Finalised
4   2018  0 days 02:18:49.277000       Ends
5   2019  0 days 00:00:06.837000   Inactive
6   2019  0 days 00:33:01.144000    Started
7   2019  0 days 02:09:50.250000   Finished
8   2019  0 days 02:12:12.407000  Finalised
9   2019  0 days 02:16:25.214000       Ends
10  2021  0 days 00:00:06.232000   Inactive
11  2021  0 days 01:02:03.441000    Started
12  2021  0 days 02:40:42.728000   Finished
13  2021  0 days 02:43:58.701000  Finalised
14  2021  0 days 02:43:58.701000       Ends
15  2022  0 days 00:00:05.422000   Inactive
16  2022  0 days 01:02:06.736000    Started
17  2022  0 days 02:40:43.657000   Finished
18  2022  0 days 02:44:40.899000  Finalised
19  2022  0 days 02:44:40.899000       Ends
20  2023  0 days 00:00:02.807000   Inactive
21  2023  0 days 01:02:18.241000    Started
22  2023  0 days 01:50:52.502000    Aborted
23  2023  0 days 02:12:00.230000    Started
24  2023  0 days 03:04:49.284000   Finished
25  2023  0 days 03:10:20.778000  Finalised
26  2023  0 days 03:10:21.450000       Ends

In [69]:
# session_status_data
# Extract days and hours
race_session_status_data['Days'] = race_session_status_data['Time'].apply(lambda x: int(x.split(' ')[0]))
race_session_status_data['Hours'] = race_session_status_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[0]))
race_session_status_data['Minutes'] = race_session_status_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[1]))

# View the updated DataFrame
print(race_session_status_data)

    Year                    Time     Status  Days  Hours  Minutes
0   2018  0 days 00:00:05.668000   Inactive     0      0        0
1   2018  0 days 00:32:58.703000    Started     0      0       32
2   2018  0 days 02:11:27.752000   Finished     0      2       11
3   2018  0 days 02:17:35.869000  Finalised     0      2       17
4   2018  0 days 02:18:49.277000       Ends     0      2       18
5   2019  0 days 00:00:06.837000   Inactive     0      0        0
6   2019  0 days 00:33:01.144000    Started     0      0       33
7   2019  0 days 02:09:50.250000   Finished     0      2        9
8   2019  0 days 02:12:12.407000  Finalised     0      2       12
9   2019  0 days 02:16:25.214000       Ends     0      2       16
10  2021  0 days 00:00:06.232000   Inactive     0      0        0
11  2021  0 days 01:02:03.441000    Started     0      1        2
12  2021  0 days 02:40:42.728000   Finished     0      2       40
13  2021  0 days 02:43:58.701000  Finalised     0      2       43
14  2021  0 days 02:43:58.701000       Ends     0      2       43
15  2022  0 days 00:00:05.422000   Inactive     0      0        0
16  2022  0 days 01:02:06.736000    Started     0      1        2
17  2022  0 days 02:40:43.657000   Finished     0      2       40
18  2022  0 days 02:44:40.899000  Finalised     0      2       44
19  2022  0 days 02:44:40.899000       Ends     0      2       44
20  2023  0 days 00:00:02.807000   Inactive     0      0        0
21  2023  0 days 01:02:18.241000    Started     0      1        2
22  2023  0 days 01:50:52.502000    Aborted     0      1       50
23  2023  0 days 02:12:00.230000    Started     0      2       12
24  2023  0 days 03:04:49.284000   Finished     0      3        4
25  2023  0 days 03:10:20.778000  Finalised     0      3       10
26  2023  0 days 03:10:21.450000       Ends     0      3       10

In [71]:
# Remove duplicates in track_status_data based on 'eventname' and 'hours'
race_session_status_data1 = race_session_status_data.drop_duplicates(subset=['Year', 'Hours', 'Minutes'])

# Now perform the left join
race_lap_data6 = pd.merge(race_lap_data5, race_session_status_data1, on=['Year', 'Hours', 'Minutes'], how='left', suffixes=('_left3', '_right3'))

# The number of rows in merged_df should now match df1

print(race_lap_data6)

      Year                  Time_x Driver  DriverNumber_left  \
0     2018  0 days 00:34:35.418000    GAS                 10
1     2018  0 days 00:36:01.984000    GAS                 10
2     2018  0 days 00:37:26.860000    GAS                 10
3     2018  0 days 00:38:54.567000    GAS                 10
4     2018  0 days 00:40:38.975000    GAS                 10
...    ...                     ...    ...                ...
6532  2023  0 days 02:59:59.540000    PIA                 81
6533  2023  0 days 03:01:22.902000    PIA                 81
6534  2023  0 days 03:02:46.070000    PIA                 81
6535  2023  0 days 03:04:09.050000    PIA                 81
6536  2023  0 days 03:05:32.471000    PIA                 81

                     LapTime  LapNumber  Stint PitOutTime  \
0     0 days 00:01:36.516000        1.0    1.0        NaN
1     0 days 00:01:26.566000        2.0    1.0        NaN
2     0 days 00:01:24.876000        3.0    1.0        NaN
3     0 days 00:01:27.707000        4.0    1.0        NaN
4     0 days 00:01:44.408000        5.0    1.0        NaN
...                      ...        ...    ...        ...
6532  0 days 00:01:23.238000       67.0    3.0        NaN
6533  0 days 00:01:23.362000       68.0    3.0        NaN
6534  0 days 00:01:23.168000       69.0    3.0        NaN
6535  0 days 00:01:22.980000       70.0    3.0        NaN
6536  0 days 00:01:23.421000       71.0    3.0        NaN

                   PitInTime             Sector1Time  ...  \
0                        NaN                     NaN  ...
1                        NaN  0 days 00:00:29.676000  ...
2                        NaN  0 days 00:00:29.359000  ...
3                        NaN  0 days 00:00:30.540000  ...
4     0 days 00:40:36.342000  0 days 00:00:41.052000  ...
...                      ...                     ...  ...
6532                     NaN  0 days 00:00:29.080000  ...
6533                     NaN  0 days 00:00:29.140000  ...
6534                     NaN  0 days 00:00:29.060000  ...
6535                     NaN  0 days 00:00:29.112000  ...
6536                     NaN  0 days 00:00:29.165000  ...

                  Time_left2 Status_right Points             Time_right2  \
0                        NaN      +2 Laps    1.0                     NaN
1                        NaN      +2 Laps    1.0                     NaN
2                        NaN      +2 Laps    1.0                     NaN
3                        NaN      +2 Laps    1.0  0 days 00:38:30.932000
4                        NaN      +2 Laps    1.0  0 days 00:40:06.874000
...                      ...          ...    ...                     ...
6532  0 days 00:00:43.104000     Finished    4.0  0 days 02:59:07.259000
6533  0 days 00:00:43.104000     Finished    4.0                     NaN
6534  0 days 00:00:43.104000     Finished    4.0                     NaN
6535  0 days 00:00:43.104000     Finished    4.0                     NaN
6536  0 days 00:00:43.104000     Finished    4.0                     NaN

     Status_left3   Message  Days_left3                    Time  \
0             NaN       NaN         NaN                     NaN
1             NaN       NaN         NaN                     NaN
2             NaN       NaN         NaN                     NaN
3             2.0    Yellow         0.0                     NaN
4             1.0  AllClear         0.0                     NaN
...           ...       ...         ...                     ...
6532          1.0  AllClear         0.0                     NaN
6533          NaN       NaN         NaN                     NaN
6534          NaN       NaN         NaN                     NaN
6535          NaN       NaN         NaN  0 days 03:04:49.284000
6536          NaN       NaN         NaN                     NaN

      Status_right3 Days_right3
0               NaN         NaN
1               NaN         NaN
2               NaN         NaN
3               NaN         NaN
4               NaN         NaN
...             ...         ...
6532            NaN         NaN
6533            NaN         NaN
6534            NaN         NaN
6535       Finished         0.0
6536            NaN         NaN

[6537 rows x 91 columns]

In [73]:
race_lap_data6.info(), race_lap_data6.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6537 entries, 0 to 6536
Data columns (total 91 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year                6537 non-null   int64
 1   Time_x              6537 non-null   object
 2   Driver              6537 non-null   object
 3   DriverNumber_left   6537 non-null   int64
 4   LapTime             6500 non-null   object
 5   LapNumber           6537 non-null   float64
 6   Stint               6537 non-null   float64
 7   PitOutTime          143 non-null    object
 8   PitInTime           150 non-null    object
 9   Sector1Time         6411 non-null   object
 10  Sector2Time         6528 non-null   object
 11  Sector3Time         6527 non-null   object
 12  Sector1SessionTime  6397 non-null   object
 13  Sector2SessionTime  6528 non-null   object
 14  Sector3SessionTime  6527 non-null   object
 15  SpeedI1             5941 non-null   float64
 16  SpeedI2             6527 non-null   float64
 17  SpeedFL             6380 non-null   float64
 18  SpeedST             5375 non-null   float64
 19  IsPersonalBest      6532 non-null   object
 20  Compound            6537 non-null   object
 21  TyreLife            6537 non-null   float64
 22  FreshTyre           6537 non-null   bool
 23  Team                6537 non-null   object
 24  LapStartTime        6537 non-null   object
 25  LapStartDate        6532 non-null   object
 26  TrackStatus         6537 non-null   int64
 27  Position_left       6530 non-null   float64
 28  Deleted             6537 non-null   bool
 29  DeletedReason       12 non-null     object
 30  FastF1Generated     6537 non-null   bool
 31  IsAccurate          6537 non-null   bool
 32  Days_x              6537 non-null   int64
 33  Hours               6537 non-null   int64
 34  Minutes             6537 non-null   int64
 35  Time_y              6537 non-null   object
 36  AirTemp             6537 non-null   float64
 37  Humidity            6537 non-null   float64
 38  Pressure            6537 non-null   float64
 39  Rainfall            6537 non-null   bool
 40  TrackTemp           6537 non-null   float64
 41  WindDirection       6537 non-null   int64
 42  WindSpeed           6537 non-null   float64
 43  Days_y              6537 non-null   int64
 44  Date_left           6537 non-null   object
 45  RPM                 6537 non-null   int64
 46  Speed               6537 non-null   int64
 47  nGear               6537 non-null   int64
 48  Throttle            6537 non-null   int64
 49  Brake               6537 non-null   bool
 50  DRS                 6537 non-null   int64
 51  Source_left         6537 non-null   object
 52  Time_left           6537 non-null   object
 53  SessionTime_left    6537 non-null   object
 54  Days_left           6537 non-null   int64
 55  Date_right          6537 non-null   object
 56  Status_left         6537 non-null   object
 57  X                   6537 non-null   int64
 58  Y                   6537 non-null   int64
 59  Z                   6537 non-null   int64
 60  Source_right        6537 non-null   object
 61  Time_right          6537 non-null   object
 62  SessionTime_right   6537 non-null   object
 63  Days_right          6537 non-null   int64
 64  DriverNumber_right  6537 non-null   int64
 65  BroadcastName       6537 non-null   object
 66  DriverId            6537 non-null   object
 67  TeamName            6537 non-null   object
 68  TeamColor           6537 non-null   object
 69  TeamId              6537 non-null   object
 70  FirstName           6537 non-null   object
 71  LastName            6537 non-null   object
 72  FullName            6537 non-null   object
 73  HeadshotUrl         5151 non-null   object
 74  CountryCode         2661 non-null   object
 75  Position_right      6537 non-null   float64
 76  ClassifiedPosition  6537 non-null   object
 77  GridPosition        6537 non-null   float64
 78  Q1                  0 non-null      float64
 79  Q2                  0 non-null      float64
 80  Q3                  0 non-null      float64
 81  Time_left2          2698 non-null   object
 82  Status_right        6537 non-null   object
 83  Points              6537 non-null   float64
 84  Time_right2         330 non-null    object
 85  Status_left3        330 non-null    float64
 86  Message             330 non-null    object
 87  Days_left3          330 non-null    float64
 88  Time                78 non-null     object
 89  Status_right3       78 non-null     object
 90  Days_right3         78 non-null     float64
dtypes: bool(6), float64(22), int64(19), object(44)
memory usage: 4.3+ MB

(None,
    Year                  Time_x Driver  DriverNumber_left  \
 0  2018  0 days 00:34:35.418000    GAS                 10
 1  2018  0 days 00:36:01.984000    GAS                 10
 2  2018  0 days 00:37:26.860000    GAS                 10
 3  2018  0 days 00:38:54.567000    GAS                 10
 4  2018  0 days 00:40:38.975000    GAS                 10

                   LapTime  LapNumber  Stint PitOutTime  \
 0  0 days 00:01:36.516000        1.0    1.0        NaN
 1  0 days 00:01:26.566000        2.0    1.0        NaN
 2  0 days 00:01:24.876000        3.0    1.0        NaN
 3  0 days 00:01:27.707000        4.0    1.0        NaN
 4  0 days 00:01:44.408000        5.0    1.0        NaN

                 PitInTime             Sector1Time  ... Time_left2  \
 0                     NaN                     NaN  ...        NaN
 1                     NaN  0 days 00:00:29.676000  ...        NaN
 2                     NaN  0 days 00:00:29.359000  ...        NaN
 3                     NaN  0 days 00:00:30.540000  ...        NaN
 4  0 days 00:40:36.342000  0 days 00:00:41.052000  ...        NaN

   Status_right Points             Time_right2 Status_left3   Message  \
 0      +2 Laps    1.0                     NaN          NaN       NaN
 1      +2 Laps    1.0                     NaN          NaN       NaN
 2      +2 Laps    1.0                     NaN          NaN       NaN
 3      +2 Laps    1.0  0 days 00:38:30.932000          2.0    Yellow
 4      +2 Laps    1.0  0 days 00:40:06.874000          1.0  AllClear

    Days_left3  Time  Status_right3 Days_right3
 0         NaN   NaN            NaN         NaN
 1         NaN   NaN            NaN         NaN
 2         NaN   NaN            NaN         NaN
 3         0.0   NaN            NaN         NaN
 4         0.0   NaN            NaN         NaN

 [5 rows x 91 columns])

In [75]:
# Save DataFrame to CSV
race_lap_data6.to_csv('race_all_data.csv', index=False)

In [ ]:
"""
# 2. circuit_data
# Extract days and hours
circuit_data['Days'] = circuit_data['Time'].apply(lambda x: int(x.split(' ')[0]))
circuit_data['Hours'] = circuit_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[0]))
circuit_data['Minutes'] = circuit_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[1]))

# View the updated DataFrame
print(circuit_data)
"""

In [ ]:
"""
# 3. control_message_data
# Extract days and hours
control_message_data['Days'] = control_message_data['Time'].apply(lambda x: int(x.split(' ')[0]))
control_message_data['Hours'] = control_message_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[0]))
control_message_data['Minutes'] = control_message_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[1]))

# View the updated DataFrame
print(control_message_data)
"""