In [1]:
# Libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# Data Access
car_data = pd.read_csv("C:/Users/yunus/Downloads/Dataset-f1/ocean_data_challenge_F1_data/races_2024/car_data_2024.csv")
circuit_data = pd.read_csv("C:/Users/yunus/Downloads/Dataset-f1/ocean_data_challenge_F1_data/races_2024/circuit_2024.csv")
control_message_data = pd.read_csv("C:/Users/yunus/Downloads/Dataset-f1/ocean_data_challenge_F1_data/races_2024/control_message_2024.csv")
lap_data = pd.read_csv("C:/Users/yunus/Downloads/Dataset-f1/ocean_data_challenge_F1_data/races_2024/lap_2024.csv", low_memory=False)
position_data = pd.read_csv("C:/Users/yunus/Downloads/Dataset-f1/ocean_data_challenge_F1_data/races_2024/position_2024.csv")
result_data = pd.read_csv("C:/Users/yunus/Downloads/Dataset-f1/ocean_data_challenge_F1_data/races_2024/result_2024.csv")
session_status_data = pd.read_csv("C:/Users/yunus/Downloads/Dataset-f1/ocean_data_challenge_F1_data/races_2024/session_status_2024.csv")
track_status_data = pd.read_csv("C:/Users/yunus/Downloads/Dataset-f1/ocean_data_challenge_F1_data/races_2024/track_status_2024.csv")
weather_data = pd.read_csv("C:/Users/yunus/Downloads/Dataset-f1/ocean_data_challenge_F1_data/races_2024/weather_2024.csv")

In [4]:
# Data Merge
# 4. Lap_data
# lap_data = pd.read_csv("C:/Users/yunus/Downloads/Dataset-f1/ocean_data_challenge_F1_data/races_2024/lap_2024.csv", low_memory=False)

In [5]:
lap_data.head()

,EventName,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,Bahrain Grand Prix,0 days 01:01:37.510000,VER,1,0 days 00:01:37.284000,1.0,1.0,NaN,NaN,NaN,...,False,Red Bull Racing,0 days 00:59:59.911000,2024-03-02 15:03:42.342,12,1.0,False,NaN,False,False
1,Bahrain Grand Prix,0 days 01:03:13.806000,VER,1,0 days 00:01:36.296000,2.0,1.0,NaN,NaN,0 days 00:00:30.916000,...,False,Red Bull Racing,0 days 01:01:37.510000,2024-03-02 15:05:19.941,1,1.0,False,NaN,False,True
2,Bahrain Grand Prix,0 days 01:04:50.559000,VER,1,0 days 00:01:36.753000,3.0,1.0,NaN,NaN,0 days 00:00:30.999000,...,False,Red Bull Racing,0 days 01:03:13.806000,2024-03-02 15:06:56.237,1,1.0,False,NaN,False,True
3,Bahrain Grand Prix,0 days 01:06:27.206000,VER,1,0 days 00:01:36.647000,4.0,1.0,NaN,NaN,0 days 00:00:30.931000,...,False,Red Bull Racing,0 days 01:04:50.559000,2024-03-02 15:08:32.990,1,1.0,False,NaN,False,True
4,Bahrain Grand Prix,0 days 01:08:04.379000,VER,1,0 days 00:01:37.173000,5.0,1.0,NaN,NaN,0 days 00:00:31.255000,...,False,Red Bull Racing,0 days 01:06:27.206000,2024-03-02 15:10:09.637,1,1.0,False,NaN,False,True

In [6]:
# lap_data
# Extract days and hours
lap_data['Days'] = lap_data['Time'].apply(lambda x: int(x.split(' ')[0]))
lap_data['Hours'] = lap_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[0]))
lap_data['Minutes'] = lap_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[1]))

# View the updated DataFrame
print(lap_data)

                EventName                    Time Driver  DriverNumber  \
0      Bahrain Grand Prix  0 days 01:01:37.510000    VER             1
1      Bahrain Grand Prix  0 days 01:03:13.806000    VER             1
2      Bahrain Grand Prix  0 days 01:04:50.559000    VER             1
3      Bahrain Grand Prix  0 days 01:06:27.206000    VER             1
4      Bahrain Grand Prix  0 days 01:08:04.379000    VER             1
...                   ...                     ...    ...           ...
17118    Dutch Grand Prix  0 days 02:23:52.192000    ZHO            24
17119    Dutch Grand Prix  0 days 02:25:07.916000    ZHO            24
17120    Dutch Grand Prix  0 days 02:26:25.673000    ZHO            24
17121    Dutch Grand Prix  0 days 02:27:41.538000    ZHO            24
17122    Dutch Grand Prix  0 days 02:28:57.336000    ZHO            24

                      LapTime  LapNumber  Stint PitOutTime PitInTime  \
0      0 days 00:01:37.284000        1.0    1.0        NaN       NaN
1      0 days 00:01:36.296000        2.0    1.0        NaN       NaN
2      0 days 00:01:36.753000        3.0    1.0        NaN       NaN
3      0 days 00:01:36.647000        4.0    1.0        NaN       NaN
4      0 days 00:01:37.173000        5.0    1.0        NaN       NaN
...                       ...        ...    ...        ...       ...
17118  0 days 00:01:15.737000       66.0    3.0        NaN       NaN
17119  0 days 00:01:15.724000       67.0    3.0        NaN       NaN
17120  0 days 00:01:17.757000       68.0    3.0        NaN       NaN
17121  0 days 00:01:15.865000       69.0    3.0        NaN       NaN
17122  0 days 00:01:15.798000       70.0    3.0        NaN       NaN

                  Sector1Time  ...             LapStartDate TrackStatus  \
0                         NaN  ...  2024-03-02 15:03:42.342          12
1      0 days 00:00:30.916000  ...  2024-03-02 15:05:19.941           1
2      0 days 00:00:30.999000  ...  2024-03-02 15:06:56.237           1
3      0 days 00:00:30.931000  ...  2024-03-02 15:08:32.990           1
4      0 days 00:00:31.255000  ...  2024-03-02 15:10:09.637           1
...                       ...  ...                      ...         ...
17118  0 days 00:00:25.857000  ...  2024-08-25 14:28:13.093           1
17119  0 days 00:00:25.746000  ...  2024-08-25 14:29:28.830           1
17120  0 days 00:00:26.736000  ...  2024-08-25 14:30:44.554           1
17121  0 days 00:00:25.980000  ...  2024-08-25 14:32:02.311           1
17122  0 days 00:00:25.776000  ...  2024-08-25 14:33:18.176           1

      Position Deleted DeletedReason  FastF1Generated  IsAccurate  Days  \
0          1.0   False           NaN            False       False     0
1          1.0   False           NaN            False        True     0
2          1.0   False           NaN            False        True     0
3          1.0   False           NaN            False        True     0
4          1.0   False           NaN            False        True     0
...        ...     ...           ...              ...         ...   ...
17118     20.0   False           NaN            False        True     0
17119     20.0   False           NaN            False        True     0
17120     20.0   False           NaN            False        True     0
17121     20.0   False           NaN            False        True     0
17122     20.0   False           NaN            False        True     0

       Hours Minutes
0          1       1
1          1       3
2          1       4
3          1       6
4          1       8
...      ...     ...
17118      2      23
17119      2      25
17120      2      26
17121      2      27
17122      2      28

[17123 rows x 35 columns]

In [11]:
# Extract days and hours
weather_data['Days'] = weather_data['Time'].apply(lambda x: int(x.split(' ')[0]))
weather_data['Hours'] = weather_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[0]))
weather_data['Minutes'] = weather_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[1]))

# View the updated DataFrame
print(weather_data)

               EventName                    Time  AirTemp  Humidity  Pressure  \
0     Bahrain Grand Prix  0 days 00:00:14.093000     18.9      46.0    1017.1
1     Bahrain Grand Prix  0 days 00:01:14.084000     18.9      46.0    1017.0
2     Bahrain Grand Prix  0 days 00:02:14.093000     18.9      46.0    1017.0
3     Bahrain Grand Prix  0 days 00:03:14.090000     18.9      45.0    1017.0
4     Bahrain Grand Prix  0 days 00:04:14.091000     18.9      46.0    1017.0
...                  ...                     ...      ...       ...       ...
2283    Dutch Grand Prix  0 days 02:28:40.944000     19.3      57.0    1019.9
2284    Dutch Grand Prix  0 days 02:29:40.939000     19.3      57.0    1019.9
2285    Dutch Grand Prix  0 days 02:30:40.913000     19.3      57.0    1019.9
2286    Dutch Grand Prix  0 days 02:31:40.918000     19.5      57.0    1020.0
2287    Dutch Grand Prix  0 days 02:32:40.913000     19.3      58.0    1020.0

      Rainfall  TrackTemp  WindDirection  WindSpeed  Days  Hours  Minutes
0        False       26.5            162        0.9     0      0        0
1        False       26.5             55        1.0     0      0        1
2        False       26.5             55        1.0     0      0        2
3        False       26.2             85        1.1     0      0        3
4        False       26.2            178        1.0     0      0        4
...        ...        ...            ...        ...   ...    ...      ...
2283     False       31.8            203        4.3     0      2       28
2284     False       31.8            203        4.3     0      2       29
2285     False       31.8            203        4.3     0      2       30
2286     False       30.8            233        4.5     0      2       31
2287     False       30.7            220        5.9     0      2       32

[2288 rows x 12 columns]

In [13]:
# Remove duplicates in weather_data based on 'eventname' and 'hours'
weather_data1 = weather_data.drop_duplicates(subset=['EventName', 'Hours', 'Minutes'])

# Now perform the left join
lap_data1 = pd.merge(lap_data, weather_data1, on=['EventName', 'Hours', 'Minutes'], how='left')

# The number of rows in merged_df should now match df1

print(lap_data1)

                EventName                  Time_x Driver  DriverNumber  \
0      Bahrain Grand Prix  0 days 01:01:37.510000    VER             1
1      Bahrain Grand Prix  0 days 01:03:13.806000    VER             1
2      Bahrain Grand Prix  0 days 01:04:50.559000    VER             1
3      Bahrain Grand Prix  0 days 01:06:27.206000    VER             1
4      Bahrain Grand Prix  0 days 01:08:04.379000    VER             1
...                   ...                     ...    ...           ...
17118    Dutch Grand Prix  0 days 02:23:52.192000    ZHO            24
17119    Dutch Grand Prix  0 days 02:25:07.916000    ZHO            24
17120    Dutch Grand Prix  0 days 02:26:25.673000    ZHO            24
17121    Dutch Grand Prix  0 days 02:27:41.538000    ZHO            24
17122    Dutch Grand Prix  0 days 02:28:57.336000    ZHO            24

                      LapTime  LapNumber  Stint PitOutTime PitInTime  \
0      0 days 00:01:37.284000        1.0    1.0        NaN       NaN
1      0 days 00:01:36.296000        2.0    1.0        NaN       NaN
2      0 days 00:01:36.753000        3.0    1.0        NaN       NaN
3      0 days 00:01:36.647000        4.0    1.0        NaN       NaN
4      0 days 00:01:37.173000        5.0    1.0        NaN       NaN
...                       ...        ...    ...        ...       ...
17118  0 days 00:01:15.737000       66.0    3.0        NaN       NaN
17119  0 days 00:01:15.724000       67.0    3.0        NaN       NaN
17120  0 days 00:01:17.757000       68.0    3.0        NaN       NaN
17121  0 days 00:01:15.865000       69.0    3.0        NaN       NaN
17122  0 days 00:01:15.798000       70.0    3.0        NaN       NaN

                  Sector1Time  ... Minutes                  Time_y AirTemp  \
0                         NaN  ...       1  0 days 01:01:14.131000    18.3
1      0 days 00:00:30.916000  ...       3  0 days 01:03:14.127000    18.3
2      0 days 00:00:30.999000  ...       4  0 days 01:04:14.121000    18.3
3      0 days 00:00:30.931000  ...       6  0 days 01:06:14.123000    18.3
4      0 days 00:00:31.255000  ...       8  0 days 01:08:14.122000    18.3
...                       ...  ...     ...                     ...     ...
17118  0 days 00:00:25.857000  ...      23  0 days 02:23:40.948000    19.3
17119  0 days 00:00:25.746000  ...      25  0 days 02:25:40.925000    19.3
17120  0 days 00:00:26.736000  ...      26  0 days 02:26:40.912000    19.3
17121  0 days 00:00:25.980000  ...      27  0 days 02:27:40.936000    19.3
17122  0 days 00:00:25.776000  ...      28  0 days 02:28:40.944000    19.3

      Humidity Pressure  Rainfall  TrackTemp  WindDirection  WindSpeed Days_y
0         49.0   1017.0     False       23.8           28.0        0.9    0.0
1         49.0   1017.1     False       23.8           89.0        1.5    0.0
2         49.0   1017.0     False       23.8           32.0        1.0    0.0
3         49.0   1017.0     False       23.6           37.0        0.7    0.0
4         50.0   1017.1     False       23.5          236.0        1.1    0.0
...        ...      ...       ...        ...            ...        ...    ...
17118     55.0   1020.1     False       31.8          213.0        4.7    0.0
17119     57.0   1019.9     False       31.8          203.0        4.3    0.0
17120     57.0   1019.9     False       31.8          203.0        4.3    0.0
17121     57.0   1019.9     False       31.8          203.0        4.3    0.0
17122     57.0   1019.9     False       31.8          203.0        4.3    0.0

[17123 rows x 44 columns]

In [15]:
lap_data1.head(), lap_data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17123 entries, 0 to 17122
Data columns (total 44 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   EventName           17123 non-null  object
 1   Time_x              17123 non-null  object
 2   Driver              17123 non-null  object
 3   DriverNumber        17123 non-null  int64
 4   LapTime             17010 non-null  object
 5   LapNumber           17123 non-null  float64
 6   Stint               17123 non-null  float64
 7   PitOutTime          554 non-null    object
 8   PitInTime           556 non-null    object
 9   Sector1Time         16788 non-null  object
 10  Sector2Time         17106 non-null  object
 11  Sector3Time         17083 non-null  object
 12  Sector1SessionTime  16750 non-null  object
 13  Sector2SessionTime  17106 non-null  object
 14  Sector3SessionTime  17083 non-null  object
 15  SpeedI1             14364 non-null  float64
 16  SpeedI2             17107 non-null  float64
 17  SpeedFL             16552 non-null  float64
 18  SpeedST             15833 non-null  float64
 19  IsPersonalBest      17115 non-null  object
 20  Compound            17123 non-null  object
 21  TyreLife            17123 non-null  float64
 22  FreshTyre           17123 non-null  bool
 23  Team                17123 non-null  object
 24  LapStartTime        17123 non-null  object
 25  LapStartDate        17115 non-null  object
 26  TrackStatus         17123 non-null  int64
 27  Position            17108 non-null  float64
 28  Deleted             17123 non-null  bool
 29  DeletedReason       173 non-null    object
 30  FastF1Generated     17123 non-null  bool
 31  IsAccurate          17123 non-null  bool
 32  Days_x              17123 non-null  int64
 33  Hours               17123 non-null  int64
 34  Minutes             17123 non-null  int64
 35  Time_y              17086 non-null  object
 36  AirTemp             17086 non-null  float64
 37  Humidity            17086 non-null  float64
 38  Pressure            17086 non-null  float64
 39  Rainfall            17086 non-null  object
 40  TrackTemp           17086 non-null  float64
 41  WindDirection       17086 non-null  float64
 42  WindSpeed           17086 non-null  float64
 43  Days_y              17086 non-null  float64
dtypes: bool(4), float64(15), int64(5), object(20)
memory usage: 5.3+ MB

(            EventName                  Time_x Driver  DriverNumber  \
 0  Bahrain Grand Prix  0 days 01:01:37.510000    VER             1
 1  Bahrain Grand Prix  0 days 01:03:13.806000    VER             1
 2  Bahrain Grand Prix  0 days 01:04:50.559000    VER             1
 3  Bahrain Grand Prix  0 days 01:06:27.206000    VER             1
 4  Bahrain Grand Prix  0 days 01:08:04.379000    VER             1

                   LapTime  LapNumber  Stint PitOutTime PitInTime  \
 0  0 days 00:01:37.284000        1.0    1.0        NaN       NaN
 1  0 days 00:01:36.296000        2.0    1.0        NaN       NaN
 2  0 days 00:01:36.753000        3.0    1.0        NaN       NaN
 3  0 days 00:01:36.647000        4.0    1.0        NaN       NaN
 4  0 days 00:01:37.173000        5.0    1.0        NaN       NaN

               Sector1Time  ... Minutes                  Time_y AirTemp  \
 0                     NaN  ...       1  0 days 01:01:14.131000    18.3
 1  0 days 00:00:30.916000  ...       3  0 days 01:03:14.127000    18.3
 2  0 days 00:00:30.999000  ...       4  0 days 01:04:14.121000    18.3
 3  0 days 00:00:30.931000  ...       6  0 days 01:06:14.123000    18.3
 4  0 days 00:00:31.255000  ...       8  0 days 01:08:14.122000    18.3

   Humidity Pressure  Rainfall  TrackTemp  WindDirection  WindSpeed Days_y
 0     49.0   1017.0     False       23.8           28.0        0.9    0.0
 1     49.0   1017.1     False       23.8           89.0        1.5    0.0
 2     49.0   1017.0     False       23.8           32.0        1.0    0.0
 3     49.0   1017.0     False       23.6           37.0        0.7    0.0
 4     50.0   1017.1     False       23.5          236.0        1.1    0.0

 [5 rows x 44 columns],
 None)

In [33]:
# car_data
# Extract days and hours
car_data['Days'] = car_data['SessionTime'].apply(lambda x: int(x.split(' ')[0]))
car_data['Hours'] = car_data['SessionTime'].apply(lambda x: int(x.split(' ')[2].split(':')[0]))
car_data['Minutes'] = car_data['SessionTime'].apply(lambda x: int(x.split(' ')[2].split(':')[1]))

# View the updated DataFrame
print(car_data)

                  EventName DriverName                     Date    RPM  Speed  \
0        Bahrain Grand Prix        VER  2024-03-02 15:03:42.390   9963      0
1        Bahrain Grand Prix        VER  2024-03-02 15:03:42.630   9755      0
2        Bahrain Grand Prix        VER  2024-03-02 15:03:42.870   8495      3
3        Bahrain Grand Prix        VER  2024-03-02 15:03:43.110   6815     11
4        Bahrain Grand Prix        VER  2024-03-02 15:03:43.270   5695     17
...                     ...        ...                      ...    ...    ...
6064736    Dutch Grand Prix        ZHO  2024-08-25 14:34:32.883  10546    296
6064737    Dutch Grand Prix        ZHO  2024-08-25 14:34:33.083  10546    298
6064738    Dutch Grand Prix        ZHO  2024-08-25 14:34:33.283  10608    298
6064739    Dutch Grand Prix        ZHO  2024-08-25 14:34:33.523  10644    298
6064740    Dutch Grand Prix        ZHO  2024-08-25 14:34:33.763  10676    300

         nGear  Throttle  Brake  DRS Source                    Time  \
0            1        15   True    1    car  0 days 00:00:00.048000
1            1        15   True    1    car  0 days 00:00:00.288000
2            1        15  False    1    car  0 days 00:00:00.528000
3            1        15  False    1    car  0 days 00:00:00.768000
4            1        15  False    1    car  0 days 00:00:00.928000
...        ...       ...    ...  ...    ...                     ...
6064736      8       100  False    0    car  0 days 01:31:20.811000
6064737      8       100  False    0    car  0 days 01:31:21.011000
6064738      8       100  False    0    car  0 days 01:31:21.211000
6064739      8       100  False    0    car  0 days 01:31:21.451000
6064740      8       100  False    0    car  0 days 01:31:21.691000

                    SessionTime  Days  Hours  Minutes
0        0 days 00:59:59.959000     0      0       59
1        0 days 01:00:00.199000     0      1        0
2        0 days 01:00:00.439000     0      1        0
3        0 days 01:00:00.679000     0      1        0
4        0 days 01:00:00.839000     0      1        0
...                         ...   ...    ...      ...
6064736  0 days 02:28:56.245000     0      2       28
6064737  0 days 02:28:56.445000     0      2       28
6064738  0 days 02:28:56.645000     0      2       28
6064739  0 days 02:28:56.885000     0      2       28
6064740  0 days 02:28:57.125000     0      2       28

[6064741 rows x 15 columns]

In [35]:
car_data.head(), car_data.info(), car_data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6064741 entries, 0 to 6064740
Data columns (total 15 columns):
 #   Column       Dtype
---  ------       -----
 0   EventName    object
 1   DriverName   object
 2   Date         object
 3   RPM          int64
 4   Speed        int64
 5   nGear        int64
 6   Throttle     int64
 7   Brake        bool
 8   DRS          int64
 9   Source       object
 10  Time         object
 11  SessionTime  object
 12  Days         int64
 13  Hours        int64
 14  Minutes      int64
dtypes: bool(1), int64(8), object(6)
memory usage: 653.6+ MB

(            EventName DriverName                     Date   RPM  Speed  nGear  \
 0  Bahrain Grand Prix        VER  2024-03-02 15:03:42.390  9963      0      1
 1  Bahrain Grand Prix        VER  2024-03-02 15:03:42.630  9755      0      1
 2  Bahrain Grand Prix        VER  2024-03-02 15:03:42.870  8495      3      1
 3  Bahrain Grand Prix        VER  2024-03-02 15:03:43.110  6815     11      1
 4  Bahrain Grand Prix        VER  2024-03-02 15:03:43.270  5695     17      1

    Throttle  Brake  DRS Source                    Time  \
 0        15   True    1    car  0 days 00:00:00.048000
 1        15   True    1    car  0 days 00:00:00.288000
 2        15  False    1    car  0 days 00:00:00.528000
 3        15  False    1    car  0 days 00:00:00.768000
 4        15  False    1    car  0 days 00:00:00.928000

               SessionTime  Days  Hours  Minutes
 0  0 days 00:59:59.959000     0      0       59
 1  0 days 01:00:00.199000     0      1        0
 2  0 days 01:00:00.439000     0      1        0
 3  0 days 01:00:00.679000     0      1        0
 4  0 days 01:00:00.839000     0      1        0  ,
 None,
                 RPM         Speed         nGear      Throttle           DRS  \
 count  6.064741e+06  6.064741e+06  6.064741e+06  6.064741e+06  6.064741e+06
 mean   9.511771e+03  1.888952e+02  4.887386e+00  5.961247e+01  7.535504e-01
 std    2.587596e+03  8.293295e+01  2.149779e+00  4.352776e+01  2.420758e+00
 min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
 25%    8.742000e+03  1.260000e+02  3.000000e+00  0.000000e+00  0.000000e+00
 50%    1.050300e+04  1.970000e+02  5.000000e+00  8.000000e+01  0.000000e+00
 75%    1.110200e+04  2.590000e+02  7.000000e+00  1.000000e+02  0.000000e+00
 max    1.349400e+04  3.560000e+02  1.280000e+02  1.040000e+02  1.500000e+01

             Days         Hours       Minutes
 count  6064741.0  6.064741e+06  6.064741e+06
 mean         0.0  1.237916e+00  2.627080e+01
 std          0.0  5.887513e-01  1.763886e+01
 min          0.0  0.000000e+00  0.000000e+00
 25%          0.0  1.000000e+00  1.100000e+01
 50%          0.0  1.000000e+00  2.300000e+01
 75%          0.0  2.000000e+00  4.100000e+01
 max          0.0  3.000000e+00  5.900000e+01  )

In [37]:
car_data.describe(include='object')

,EventName,DriverName,Date,Source,Time,SessionTime
count,6064741,6064741,6064741,6064741,6064741,6064741
unique,15,21,325127,1,315731,319116
top,Monaco Grand Prix,ALO,2024-03-02 15:03:42.390,car,0 days 00:09:18.249000,0 days 01:21:43.974000
freq,557162,323234,20,6064741,60,58

In [38]:
# Remove duplicates in weather_data based on 'eventname' and 'hours'
car_data1 = car_data.drop_duplicates(subset=['EventName', 'DriverName', 'Hours', 'Minutes'])

In [40]:
car_data1.rename(columns={'DriverName': 'Driver'}, inplace=True)

C:\Users\yunus\AppData\Local\Temp\ipykernel_6328\3107254745.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  car_data1.rename(columns={'DriverName': 'Driver'}, inplace=True)

In [43]:
car_data1.head(), car_data1.info(), car_data1.describe(), car_data1.describe(include='object')

<class 'pandas.core.frame.DataFrame'>
Index: 27108 entries, 0 to 6064523
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EventName    27108 non-null  object
 1   Driver       27108 non-null  object
 2   Date         27108 non-null  object
 3   RPM          27108 non-null  int64
 4   Speed        27108 non-null  int64
 5   nGear        27108 non-null  int64
 6   Throttle     27108 non-null  int64
 7   Brake        27108 non-null  bool
 8   DRS          27108 non-null  int64
 9   Source       27108 non-null  object
 10  Time         27108 non-null  object
 11  SessionTime  27108 non-null  object
 12  Days         27108 non-null  int64
 13  Hours        27108 non-null  int64
 14  Minutes      27108 non-null  int64
dtypes: bool(1), int64(8), object(6)
memory usage: 3.1+ MB

(              EventName Driver                     Date    RPM  Speed  nGear  \
 0    Bahrain Grand Prix    VER  2024-03-02 15:03:42.390   9963      0      1
 1    Bahrain Grand Prix    VER  2024-03-02 15:03:42.630   9755      0      1
 223  Bahrain Grand Prix    VER  2024-03-02 15:04:42.550  10702    267      7
 453  Bahrain Grand Prix    VER  2024-03-02 15:05:42.670  10124    262      7
 687  Bahrain Grand Prix    VER  2024-03-02 15:06:42.670  11173    282      7

      Throttle  Brake  DRS Source                    Time  \
 0          15   True    1    car  0 days 00:00:00.048000
 1          15   True    1    car  0 days 00:00:00.288000
 223       100  False    1    car  0 days 00:01:00.208000
 453         0   True    0    car  0 days 00:02:00.328000
 687       100  False    0    car  0 days 00:03:00.328000

                 SessionTime  Days  Hours  Minutes
 0    0 days 00:59:59.959000     0      0       59
 1    0 days 01:00:00.199000     0      1        0
 223  0 days 01:01:00.119000     0      1        1
 453  0 days 01:02:00.239000     0      1        2
 687  0 days 01:03:00.239000     0      1        3  ,
 None,
                 RPM         Speed         nGear      Throttle           DRS  \
 count  27108.000000  27108.000000  27108.000000  27108.000000  27108.000000
 mean    9519.373174    186.401247      4.827394     59.332485      0.758189
 std     2576.099061     84.647134      2.137518     43.317963      2.402593
 min        0.000000      0.000000      0.000000      0.000000      0.000000
 25%     8769.750000    123.000000      3.000000      0.000000      0.000000
 50%    10502.000000    195.000000      5.000000     78.000000      0.000000
 75%    11101.000000    257.000000      7.000000    100.000000      0.000000
 max    12612.000000    342.000000      8.000000    104.000000     14.000000

           Days         Hours       Minutes
 count  27108.0  27108.000000  27108.000000
 mean       0.0      1.234838     26.426332
 std        0.0      0.595262     17.698835
 min        0.0      0.000000      0.000000
 25%        0.0      1.000000     11.000000
 50%        0.0      1.000000     24.000000
 75%        0.0      2.000000     41.000000
 max        0.0      3.000000     59.000000  ,
                 EventName Driver                     Date Source  \
 count               27108  27108                    27108  27108
 unique                 15     21                     1452      1
 top     Monaco Grand Prix    ALO  2024-03-02 15:03:42.390    car
 freq                 2476   1444                       20  27108

                           Time             SessionTime
 count                    27108                   27108
 unique                    1447                    1430
 top     0 days 00:29:54.453000  0 days 01:01:00.119000
 freq                        40                      40  )

In [45]:
# Remove duplicates in weather_data based on 'eventname' and 'hours'
# car_data1 = car_data.drop_duplicates(subset=['EventName', 'DriverName', 'Hours', 'Minutes'])

# Now perform the left join
lap_data2 = pd.merge(lap_data1, car_data1, on=['EventName', 'Driver', 'Hours', 'Minutes'], how='left')

# The number of rows in merged_df should now match df1

print(lap_data2)

                EventName                  Time_x Driver  DriverNumber  \
0      Bahrain Grand Prix  0 days 01:01:37.510000    VER             1
1      Bahrain Grand Prix  0 days 01:03:13.806000    VER             1
2      Bahrain Grand Prix  0 days 01:04:50.559000    VER             1
3      Bahrain Grand Prix  0 days 01:06:27.206000    VER             1
4      Bahrain Grand Prix  0 days 01:08:04.379000    VER             1
...                   ...                     ...    ...           ...
17118    Dutch Grand Prix  0 days 02:23:52.192000    ZHO            24
17119    Dutch Grand Prix  0 days 02:25:07.916000    ZHO            24
17120    Dutch Grand Prix  0 days 02:26:25.673000    ZHO            24
17121    Dutch Grand Prix  0 days 02:27:41.538000    ZHO            24
17122    Dutch Grand Prix  0 days 02:28:57.336000    ZHO            24

                      LapTime  LapNumber  Stint PitOutTime PitInTime  \
0      0 days 00:01:37.284000        1.0    1.0        NaN       NaN
1      0 days 00:01:36.296000        2.0    1.0        NaN       NaN
2      0 days 00:01:36.753000        3.0    1.0        NaN       NaN
3      0 days 00:01:36.647000        4.0    1.0        NaN       NaN
4      0 days 00:01:37.173000        5.0    1.0        NaN       NaN
...                       ...        ...    ...        ...       ...
17118  0 days 00:01:15.737000       66.0    3.0        NaN       NaN
17119  0 days 00:01:15.724000       67.0    3.0        NaN       NaN
17120  0 days 00:01:17.757000       68.0    3.0        NaN       NaN
17121  0 days 00:01:15.865000       69.0    3.0        NaN       NaN
17122  0 days 00:01:15.798000       70.0    3.0        NaN       NaN

                  Sector1Time  ...    RPM Speed nGear Throttle  Brake  DRS  \
0                         NaN  ...  10702   267     7      100  False    1
1      0 days 00:00:30.916000  ...  11173   282     7      100  False    0
2      0 days 00:00:30.999000  ...  10612   235     6      100  False    0
3      0 days 00:00:30.931000  ...  10914   244     6       75  False    0
4      0 days 00:00:31.255000  ...  11516   224     5      100  False    0
...                       ...  ...    ...   ...   ...      ...    ...  ...
17118  0 days 00:00:25.857000  ...  11290   282     7      100  False    0
17119  0 days 00:00:25.746000  ...  10945   239     6      100  False    0
17120  0 days 00:00:26.736000  ...  11245   238     6      100  False   12
17121  0 days 00:00:25.980000  ...   9821   212     6      100  False    0
17122  0 days 00:00:25.776000  ...  10954   204     5      100  False    0

       Source                    Time             SessionTime Days
0         car  0 days 00:01:00.208000  0 days 01:01:00.119000    0
1         car  0 days 00:03:00.328000  0 days 01:03:00.239000    0
2         car  0 days 00:04:00.208000  0 days 01:04:00.119000    0
3         car  0 days 00:06:00.208000  0 days 01:06:00.119000    0
4         car  0 days 00:08:00.168000  0 days 01:08:00.079000    0
...       ...                     ...                     ...  ...
17118     car  0 days 01:25:24.930000  0 days 02:23:00.364000    0
17119     car  0 days 01:27:24.610000  0 days 02:25:00.044000    0
17120     car  0 days 01:28:24.970000  0 days 02:26:00.404000    0
17121     car  0 days 01:29:24.650000  0 days 02:27:00.084000    0
17122     car  0 days 01:30:24.690000  0 days 02:28:00.124000    0

[17123 rows x 55 columns]

In [47]:
lap_data2.head(), lap_data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17123 entries, 0 to 17122
Data columns (total 55 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   EventName           17123 non-null  object
 1   Time_x              17123 non-null  object
 2   Driver              17123 non-null  object
 3   DriverNumber        17123 non-null  int64
 4   LapTime             17010 non-null  object
 5   LapNumber           17123 non-null  float64
 6   Stint               17123 non-null  float64
 7   PitOutTime          554 non-null    object
 8   PitInTime           556 non-null    object
 9   Sector1Time         16788 non-null  object
 10  Sector2Time         17106 non-null  object
 11  Sector3Time         17083 non-null  object
 12  Sector1SessionTime  16750 non-null  object
 13  Sector2SessionTime  17106 non-null  object
 14  Sector3SessionTime  17083 non-null  object
 15  SpeedI1             14364 non-null  float64
 16  SpeedI2             17107 non-null  float64
 17  SpeedFL             16552 non-null  float64
 18  SpeedST             15833 non-null  float64
 19  IsPersonalBest      17115 non-null  object
 20  Compound            17123 non-null  object
 21  TyreLife            17123 non-null  float64
 22  FreshTyre           17123 non-null  bool
 23  Team                17123 non-null  object
 24  LapStartTime        17123 non-null  object
 25  LapStartDate        17115 non-null  object
 26  TrackStatus         17123 non-null  int64
 27  Position            17108 non-null  float64
 28  Deleted             17123 non-null  bool
 29  DeletedReason       173 non-null    object
 30  FastF1Generated     17123 non-null  bool
 31  IsAccurate          17123 non-null  bool
 32  Days_x              17123 non-null  int64
 33  Hours               17123 non-null  int64
 34  Minutes             17123 non-null  int64
 35  Time_y              17086 non-null  object
 36  AirTemp             17086 non-null  float64
 37  Humidity            17086 non-null  float64
 38  Pressure            17086 non-null  float64
 39  Rainfall            17086 non-null  object
 40  TrackTemp           17086 non-null  float64
 41  WindDirection       17086 non-null  float64
 42  WindSpeed           17086 non-null  float64
 43  Days_y              17086 non-null  float64
 44  Date                17123 non-null  object
 45  RPM                 17123 non-null  int64
 46  Speed               17123 non-null  int64
 47  nGear               17123 non-null  int64
 48  Throttle            17123 non-null  int64
 49  Brake               17123 non-null  bool
 50  DRS                 17123 non-null  int64
 51  Source              17123 non-null  object
 52  Time                17123 non-null  object
 53  SessionTime         17123 non-null  object
 54  Days                17123 non-null  int64
dtypes: bool(5), float64(15), int64(11), object(24)
memory usage: 6.6+ MB

(            EventName                  Time_x Driver  DriverNumber  \
 0  Bahrain Grand Prix  0 days 01:01:37.510000    VER             1
 1  Bahrain Grand Prix  0 days 01:03:13.806000    VER             1
 2  Bahrain Grand Prix  0 days 01:04:50.559000    VER             1
 3  Bahrain Grand Prix  0 days 01:06:27.206000    VER             1
 4  Bahrain Grand Prix  0 days 01:08:04.379000    VER             1

                   LapTime  LapNumber  Stint PitOutTime PitInTime  \
 0  0 days 00:01:37.284000        1.0    1.0        NaN       NaN
 1  0 days 00:01:36.296000        2.0    1.0        NaN       NaN
 2  0 days 00:01:36.753000        3.0    1.0        NaN       NaN
 3  0 days 00:01:36.647000        4.0    1.0        NaN       NaN
 4  0 days 00:01:37.173000        5.0    1.0        NaN       NaN

               Sector1Time  ...    RPM Speed nGear Throttle  Brake  DRS  \
 0                     NaN  ...  10702   267     7      100  False    1
 1  0 days 00:00:30.916000  ...  11173   282     7      100  False    0
 2  0 days 00:00:30.999000  ...  10612   235     6      100  False    0
 3  0 days 00:00:30.931000  ...  10914   244     6       75  False    0
 4  0 days 00:00:31.255000  ...  11516   224     5      100  False    0

    Source                    Time             SessionTime Days
 0     car  0 days 00:01:00.208000  0 days 01:01:00.119000    0
 1     car  0 days 00:03:00.328000  0 days 01:03:00.239000    0
 2     car  0 days 00:04:00.208000  0 days 01:04:00.119000    0
 3     car  0 days 00:06:00.208000  0 days 01:06:00.119000    0
 4     car  0 days 00:08:00.168000  0 days 01:08:00.079000    0

 [5 rows x 55 columns],
 None)

In [49]:
# Data Merge
# 5. position
position_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10483751 entries, 0 to 10483750
Data columns (total 10 columns):
 #   Column       Dtype
---  ------       -----
 0   EventName    object
 1   DriverName   object
 2   Date         object
 3   Status       object
 4   X            float64
 5   Y            float64
 6   Z            float64
 7   Source       object
 8   Time         object
 9   SessionTime  object
dtypes: float64(3), object(7)
memory usage: 799.8+ MB

In [53]:
position_data.head(), position_data.tail()

(            EventName DriverName                     Date   Status    X    Y  \
 0  Bahrain Grand Prix        VER  2024-03-02 14:03:43.899  OnTrack  0.0  0.0
 1  Bahrain Grand Prix        VER  2024-03-02 14:03:44.219  OnTrack  0.0  0.0
 2  Bahrain Grand Prix        VER  2024-03-02 14:03:44.460  OnTrack  0.0  0.0
 3  Bahrain Grand Prix        VER  2024-03-02 14:03:44.720  OnTrack  0.0  0.0
 4  Bahrain Grand Prix        VER  2024-03-02 14:03:45.000  OnTrack  0.0  0.0

      Z Source                    Time             SessionTime
 0  0.0    pos  0 days 00:00:01.468000  0 days 00:00:01.468000
 1  0.0    pos  0 days 00:00:01.788000  0 days 00:00:01.788000
 2  0.0    pos  0 days 00:00:02.029000  0 days 00:00:02.029000
 3  0.0    pos  0 days 00:00:02.289000  0 days 00:00:02.289000
 4  0.0    pos  0 days 00:00:02.569000  0 days 00:00:02.569000  ,
                  EventName DriverName                     Date   Status  \
 10483746  Dutch Grand Prix        ZHO  2024-08-25 14:38:21.097  OnTrack
 10483747  Dutch Grand Prix        ZHO  2024-08-25 14:38:21.556  OnTrack
 10483748  Dutch Grand Prix        ZHO  2024-08-25 14:38:21.896  OnTrack
 10483749  Dutch Grand Prix        ZHO  2024-08-25 14:38:22.096  OnTrack
 10483750  Dutch Grand Prix        ZHO  2024-08-25 14:38:22.496  OnTrack

               X       Y      Z Source                    Time  \
 10483746  319.0  2937.0  537.0    pos  0 days 02:32:44.459000
 10483747  319.0  2937.0  537.0    pos  0 days 02:32:44.918000
 10483748  319.0  2937.0  537.0    pos  0 days 02:32:45.258000
 10483749  319.0  2937.0  537.0    pos  0 days 02:32:45.458000
 10483750  319.0  2937.0  537.0    pos  0 days 02:32:45.858000

                      SessionTime
 10483746  0 days 02:32:44.459000
 10483747  0 days 02:32:44.918000
 10483748  0 days 02:32:45.258000
 10483749  0 days 02:32:45.458000
 10483750  0 days 02:32:45.858000  )

In [55]:
position_data.rename(columns={'DriverName': 'Driver'}, inplace=True)

In [57]:
# position_data
# Extract days and hours
position_data['Days'] = position_data['Time'].apply(lambda x: int(x.split(' ')[0]))
position_data['Hours'] = position_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[0]))
position_data['Minutes'] = position_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[1]))

# View the updated DataFrame
print(position_data)

                   EventName Driver                     Date   Status      X  \
0         Bahrain Grand Prix    VER  2024-03-02 14:03:43.899  OnTrack    0.0
1         Bahrain Grand Prix    VER  2024-03-02 14:03:44.219  OnTrack    0.0
2         Bahrain Grand Prix    VER  2024-03-02 14:03:44.460  OnTrack    0.0
3         Bahrain Grand Prix    VER  2024-03-02 14:03:44.720  OnTrack    0.0
4         Bahrain Grand Prix    VER  2024-03-02 14:03:45.000  OnTrack    0.0
...                      ...    ...                      ...      ...    ...
10483746    Dutch Grand Prix    ZHO  2024-08-25 14:38:21.097  OnTrack  319.0
10483747    Dutch Grand Prix    ZHO  2024-08-25 14:38:21.556  OnTrack  319.0
10483748    Dutch Grand Prix    ZHO  2024-08-25 14:38:21.896  OnTrack  319.0
10483749    Dutch Grand Prix    ZHO  2024-08-25 14:38:22.096  OnTrack  319.0
10483750    Dutch Grand Prix    ZHO  2024-08-25 14:38:22.496  OnTrack  319.0

               Y      Z Source                    Time  \
0            0.0    0.0    pos  0 days 00:00:01.468000
1            0.0    0.0    pos  0 days 00:00:01.788000
2            0.0    0.0    pos  0 days 00:00:02.029000
3            0.0    0.0    pos  0 days 00:00:02.289000
4            0.0    0.0    pos  0 days 00:00:02.569000
...          ...    ...    ...                     ...
10483746  2937.0  537.0    pos  0 days 02:32:44.459000
10483747  2937.0  537.0    pos  0 days 02:32:44.918000
10483748  2937.0  537.0    pos  0 days 02:32:45.258000
10483749  2937.0  537.0    pos  0 days 02:32:45.458000
10483750  2937.0  537.0    pos  0 days 02:32:45.858000

                     SessionTime  Days  Hours  Minutes
0         0 days 00:00:01.468000     0      0        0
1         0 days 00:00:01.788000     0      0        0
2         0 days 00:00:02.029000     0      0        0
3         0 days 00:00:02.289000     0      0        0
4         0 days 00:00:02.569000     0      0        0
...                          ...   ...    ...      ...
10483746  0 days 02:32:44.459000     0      2       32
10483747  0 days 02:32:44.918000     0      2       32
10483748  0 days 02:32:45.258000     0      2       32
10483749  0 days 02:32:45.458000     0      2       32
10483750  0 days 02:32:45.858000     0      2       32

[10483751 rows x 13 columns]

In [59]:
# Remove duplicates in position_data based on 'eventname' and 'hours'
position_data1 = position_data.drop_duplicates(subset=['EventName', 'Driver', 'Hours', 'Minutes'])

# Now perform the left join
lap_data3 = pd.merge(lap_data2, position_data1, on=['EventName', 'Driver', 'Hours', 'Minutes'], how='left', suffixes=('_left', '_right'))

# The number of rows in merged_df should now match df1

print(lap_data3)

                EventName                  Time_x Driver  DriverNumber  \
0      Bahrain Grand Prix  0 days 01:01:37.510000    VER             1
1      Bahrain Grand Prix  0 days 01:03:13.806000    VER             1
2      Bahrain Grand Prix  0 days 01:04:50.559000    VER             1
3      Bahrain Grand Prix  0 days 01:06:27.206000    VER             1
4      Bahrain Grand Prix  0 days 01:08:04.379000    VER             1
...                   ...                     ...    ...           ...
17118    Dutch Grand Prix  0 days 02:23:52.192000    ZHO            24
17119    Dutch Grand Prix  0 days 02:25:07.916000    ZHO            24
17120    Dutch Grand Prix  0 days 02:26:25.673000    ZHO            24
17121    Dutch Grand Prix  0 days 02:27:41.538000    ZHO            24
17122    Dutch Grand Prix  0 days 02:28:57.336000    ZHO            24

                      LapTime  LapNumber  Stint PitOutTime PitInTime  \
0      0 days 00:01:37.284000        1.0    1.0        NaN       NaN
1      0 days 00:01:36.296000        2.0    1.0        NaN       NaN
2      0 days 00:01:36.753000        3.0    1.0        NaN       NaN
3      0 days 00:01:36.647000        4.0    1.0        NaN       NaN
4      0 days 00:01:37.173000        5.0    1.0        NaN       NaN
...                       ...        ...    ...        ...       ...
17118  0 days 00:01:15.737000       66.0    3.0        NaN       NaN
17119  0 days 00:01:15.724000       67.0    3.0        NaN       NaN
17120  0 days 00:01:17.757000       68.0    3.0        NaN       NaN
17121  0 days 00:01:15.865000       69.0    3.0        NaN       NaN
17122  0 days 00:01:15.798000       70.0    3.0        NaN       NaN

                  Sector1Time  ... Days_left               Date_right  \
0                         NaN  ...         0  2024-03-02 15:04:42.719
1      0 days 00:00:30.916000  ...         0  2024-03-02 15:06:42.499
2      0 days 00:00:30.999000  ...         0  2024-03-02 15:07:42.519
3      0 days 00:00:30.931000  ...         0  2024-03-02 15:09:42.459
4      0 days 00:00:31.255000  ...         0  2024-03-02 15:11:42.499
...                       ...  ...       ...                      ...
17118  0 days 00:00:25.857000  ...         0  2024-08-25 14:28:36.796
17119  0 days 00:00:25.746000  ...         0  2024-08-25 14:30:36.736
17120  0 days 00:00:26.736000  ...         0  2024-08-25 14:31:37.177
17121  0 days 00:00:25.980000  ...         0  2024-08-25 14:32:36.657
17122  0 days 00:00:25.776000  ...         0  2024-08-25 14:33:36.717

        Status       X       Y      Z  Source_right              Time_right  \
0      OnTrack  1629.0  2526.0 -139.0           pos  0 days 01:01:00.288000
1      OnTrack  2945.0 -1979.0  -79.0           pos  0 days 01:03:00.068000
2      OnTrack  2682.0  4934.0 -104.0           pos  0 days 01:04:00.088000
3      OnTrack  3843.0  1178.0  -49.0           pos  0 days 01:06:00.028000
4      OnTrack  -543.0 -1754.0 -152.0           pos  0 days 01:08:00.068000
...        ...     ...     ...    ...           ...                     ...
17118  OnTrack  5366.0  3180.0  531.0           pos  0 days 02:23:00.158000
17119  OnTrack   -75.0 -1470.0  538.0           pos  0 days 02:25:00.098000
17120  OnTrack  4991.0  2546.0  538.0           pos  0 days 02:26:00.539000
17121  OnTrack  6958.0    66.0  523.0           pos  0 days 02:27:00.019000
17122  OnTrack  1923.0  2855.0  590.0           pos  0 days 02:28:00.079000

            SessionTime_right Days_right
0      0 days 01:01:00.288000          0
1      0 days 01:03:00.068000          0
2      0 days 01:04:00.088000          0
3      0 days 01:06:00.028000          0
4      0 days 01:08:00.068000          0
...                       ...        ...
17118  0 days 02:23:00.158000          0
17119  0 days 02:25:00.098000          0
17120  0 days 02:26:00.539000          0
17121  0 days 02:27:00.019000          0
17122  0 days 02:28:00.079000          0

[17123 rows x 64 columns]

In [61]:
lap_data3.head(), lap_data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17123 entries, 0 to 17122
Data columns (total 64 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   EventName           17123 non-null  object
 1   Time_x              17123 non-null  object
 2   Driver              17123 non-null  object
 3   DriverNumber        17123 non-null  int64
 4   LapTime             17010 non-null  object
 5   LapNumber           17123 non-null  float64
 6   Stint               17123 non-null  float64
 7   PitOutTime          554 non-null    object
 8   PitInTime           556 non-null    object
 9   Sector1Time         16788 non-null  object
 10  Sector2Time         17106 non-null  object
 11  Sector3Time         17083 non-null  object
 12  Sector1SessionTime  16750 non-null  object
 13  Sector2SessionTime  17106 non-null  object
 14  Sector3SessionTime  17083 non-null  object
 15  SpeedI1             14364 non-null  float64
 16  SpeedI2             17107 non-null  float64
 17  SpeedFL             16552 non-null  float64
 18  SpeedST             15833 non-null  float64
 19  IsPersonalBest      17115 non-null  object
 20  Compound            17123 non-null  object
 21  TyreLife            17123 non-null  float64
 22  FreshTyre           17123 non-null  bool
 23  Team                17123 non-null  object
 24  LapStartTime        17123 non-null  object
 25  LapStartDate        17115 non-null  object
 26  TrackStatus         17123 non-null  int64
 27  Position            17108 non-null  float64
 28  Deleted             17123 non-null  bool
 29  DeletedReason       173 non-null    object
 30  FastF1Generated     17123 non-null  bool
 31  IsAccurate          17123 non-null  bool
 32  Days_x              17123 non-null  int64
 33  Hours               17123 non-null  int64
 34  Minutes             17123 non-null  int64
 35  Time_y              17086 non-null  object
 36  AirTemp             17086 non-null  float64
 37  Humidity            17086 non-null  float64
 38  Pressure            17086 non-null  float64
 39  Rainfall            17086 non-null  object
 40  TrackTemp           17086 non-null  float64
 41  WindDirection       17086 non-null  float64
 42  WindSpeed           17086 non-null  float64
 43  Days_y              17086 non-null  float64
 44  Date_left           17123 non-null  object
 45  RPM                 17123 non-null  int64
 46  Speed               17123 non-null  int64
 47  nGear               17123 non-null  int64
 48  Throttle            17123 non-null  int64
 49  Brake               17123 non-null  bool
 50  DRS                 17123 non-null  int64
 51  Source_left         17123 non-null  object
 52  Time_left           17123 non-null  object
 53  SessionTime_left    17123 non-null  object
 54  Days_left           17123 non-null  int64
 55  Date_right          17123 non-null  object
 56  Status              17123 non-null  object
 57  X                   17123 non-null  float64
 58  Y                   17123 non-null  float64
 59  Z                   17123 non-null  float64
 60  Source_right        17123 non-null  object
 61  Time_right          17123 non-null  object
 62  SessionTime_right   17123 non-null  object
 63  Days_right          17123 non-null  int64
dtypes: bool(5), float64(18), int64(12), object(29)
memory usage: 7.8+ MB

(            EventName                  Time_x Driver  DriverNumber  \
 0  Bahrain Grand Prix  0 days 01:01:37.510000    VER             1
 1  Bahrain Grand Prix  0 days 01:03:13.806000    VER             1
 2  Bahrain Grand Prix  0 days 01:04:50.559000    VER             1
 3  Bahrain Grand Prix  0 days 01:06:27.206000    VER             1
 4  Bahrain Grand Prix  0 days 01:08:04.379000    VER             1

                   LapTime  LapNumber  Stint PitOutTime PitInTime  \
 0  0 days 00:01:37.284000        1.0    1.0        NaN       NaN
 1  0 days 00:01:36.296000        2.0    1.0        NaN       NaN
 2  0 days 00:01:36.753000        3.0    1.0        NaN       NaN
 3  0 days 00:01:36.647000        4.0    1.0        NaN       NaN
 4  0 days 00:01:37.173000        5.0    1.0        NaN       NaN

               Sector1Time  ... Days_left               Date_right   Status  \
 0                     NaN  ...         0  2024-03-02 15:04:42.719  OnTrack
 1  0 days 00:00:30.916000  ...         0  2024-03-02 15:06:42.499  OnTrack
 2  0 days 00:00:30.999000  ...         0  2024-03-02 15:07:42.519  OnTrack
 3  0 days 00:00:30.931000  ...         0  2024-03-02 15:09:42.459  OnTrack
 4  0 days 00:00:31.255000  ...         0  2024-03-02 15:11:42.499  OnTrack

         X       Y      Z  Source_right              Time_right  \
 0  1629.0  2526.0 -139.0           pos  0 days 01:01:00.288000
 1  2945.0 -1979.0  -79.0           pos  0 days 01:03:00.068000
 2  2682.0  4934.0 -104.0           pos  0 days 01:04:00.088000
 3  3843.0  1178.0  -49.0           pos  0 days 01:06:00.028000
 4  -543.0 -1754.0 -152.0           pos  0 days 01:08:00.068000

         SessionTime_right Days_right
 0  0 days 01:01:00.288000          0
 1  0 days 01:03:00.068000          0
 2  0 days 01:04:00.088000          0
 3  0 days 01:06:00.028000          0
 4  0 days 01:08:00.068000          0

 [5 rows x 64 columns],
 None)

In [63]:
# Data Merge
# 6. result_data

In [69]:
result_data.info(), result_data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   EventName           299 non-null    object
 1   DriverNumber        299 non-null    int64
 2   BroadcastName       299 non-null    object
 3   Abbreviation        299 non-null    object
 4   DriverId            299 non-null    object
 5   TeamName            299 non-null    object
 6   TeamColor           299 non-null    object
 7   TeamId              299 non-null    object
 8   FirstName           299 non-null    object
 9   LastName            299 non-null    object
 10  FullName            299 non-null    object
 11  HeadshotUrl         298 non-null    object
 12  CountryCode         299 non-null    object
 13  Position            299 non-null    float64
 14  ClassifiedPosition  299 non-null    object
 15  GridPosition        299 non-null    float64
 16  Q1                  0 non-null      float64
 17  Q2                  0 non-null      float64
 18  Q3                  0 non-null      float64
 19  Time                179 non-null    object
 20  Status              299 non-null    object
 21  Points              299 non-null    float64
dtypes: float64(6), int64(1), object(15)
memory usage: 51.5+ KB

(None,
             EventName  DriverNumber BroadcastName Abbreviation  \
 0  Bahrain Grand Prix             1  M VERSTAPPEN          VER
 1  Bahrain Grand Prix            11       S PEREZ          PER
 2  Bahrain Grand Prix            55       C SAINZ          SAI
 3  Bahrain Grand Prix            16     C LECLERC          LEC
 4  Bahrain Grand Prix            63     G RUSSELL          RUS

          DriverId         TeamName TeamColor    TeamId FirstName    LastName  \
 0  max_verstappen  Red Bull Racing    3671c6  red_bull       Max  Verstappen
 1           perez  Red Bull Racing    3671c6  red_bull    Sergio       Perez
 2           sainz          Ferrari    e8002d   ferrari    Carlos       Sainz
 3         leclerc          Ferrari    e8002d   ferrari   Charles     Leclerc
 4         russell         Mercedes    27f4d2  mercedes    George     Russell

    ... CountryCode Position ClassifiedPosition  GridPosition  Q1  Q2  Q3  \
 0  ...         NED      1.0                  1           1.0 NaN NaN NaN
 1  ...         MEX      2.0                  2           5.0 NaN NaN NaN
 2  ...         ESP      3.0                  3           4.0 NaN NaN NaN
 3  ...         MON      4.0                  4           2.0 NaN NaN NaN
 4  ...         GBR      5.0                  5           3.0 NaN NaN NaN

                      Time    Status Points
 0  0 days 01:31:44.742000  Finished   26.0
 1  0 days 00:00:22.457000  Finished   18.0
 2  0 days 00:00:25.110000  Finished   15.0
 3  0 days 00:00:39.669000  Finished   12.0
 4  0 days 00:00:46.788000  Finished   10.0

 [5 rows x 22 columns])

In [71]:
result_data.rename(columns={'Abbreviation': 'Driver'}, inplace=True)

In [73]:
# Remove duplicates in result_data based on 'eventname' and 'hours'
# result_data1 = result_data.drop_duplicates(subset=['EventName', 'Hours', 'Minutes'])

# Now perform the left join
lap_data4 = pd.merge(lap_data3, result_data, on=['EventName', 'Driver'], how='left', suffixes=('_left', '_right'))

# The number of rows in merged_df should now match df1

print(lap_data4)

                EventName                  Time_x Driver  DriverNumber_left  \
0      Bahrain Grand Prix  0 days 01:01:37.510000    VER                  1
1      Bahrain Grand Prix  0 days 01:03:13.806000    VER                  1
2      Bahrain Grand Prix  0 days 01:04:50.559000    VER                  1
3      Bahrain Grand Prix  0 days 01:06:27.206000    VER                  1
4      Bahrain Grand Prix  0 days 01:08:04.379000    VER                  1
...                   ...                     ...    ...                ...
17118    Dutch Grand Prix  0 days 02:23:52.192000    ZHO                 24
17119    Dutch Grand Prix  0 days 02:25:07.916000    ZHO                 24
17120    Dutch Grand Prix  0 days 02:26:25.673000    ZHO                 24
17121    Dutch Grand Prix  0 days 02:27:41.538000    ZHO                 24
17122    Dutch Grand Prix  0 days 02:28:57.336000    ZHO                 24

                      LapTime  LapNumber  Stint PitOutTime PitInTime  \
0      0 days 00:01:37.284000        1.0    1.0        NaN       NaN
1      0 days 00:01:36.296000        2.0    1.0        NaN       NaN
2      0 days 00:01:36.753000        3.0    1.0        NaN       NaN
3      0 days 00:01:36.647000        4.0    1.0        NaN       NaN
4      0 days 00:01:37.173000        5.0    1.0        NaN       NaN
...                       ...        ...    ...        ...       ...
17118  0 days 00:01:15.737000       66.0    3.0        NaN       NaN
17119  0 days 00:01:15.724000       67.0    3.0        NaN       NaN
17120  0 days 00:01:17.757000       68.0    3.0        NaN       NaN
17121  0 days 00:01:15.865000       69.0    3.0        NaN       NaN
17122  0 days 00:01:15.798000       70.0    3.0        NaN       NaN

                  Sector1Time  ... CountryCode Position_right  \
0                         NaN  ...         NED            1.0
1      0 days 00:00:30.916000  ...         NED            1.0
2      0 days 00:00:30.999000  ...         NED            1.0
3      0 days 00:00:30.931000  ...         NED            1.0
4      0 days 00:00:31.255000  ...         NED            1.0
...                       ...  ...         ...            ...
17118  0 days 00:00:25.857000  ...         CHN           20.0
17119  0 days 00:00:25.746000  ...         CHN           20.0
17120  0 days 00:00:26.736000  ...         CHN           20.0
17121  0 days 00:00:25.980000  ...         CHN           20.0
17122  0 days 00:00:25.776000  ...         CHN           20.0

      ClassifiedPosition GridPosition  Q1  Q2  Q3                    Time  \
0                      1          1.0 NaN NaN NaN  0 days 01:31:44.742000
1                      1          1.0 NaN NaN NaN  0 days 01:31:44.742000
2                      1          1.0 NaN NaN NaN  0 days 01:31:44.742000
3                      1          1.0 NaN NaN NaN  0 days 01:31:44.742000
4                      1          1.0 NaN NaN NaN  0 days 01:31:44.742000
...                  ...          ...  ..  ..  ..                     ...
17118                 20         17.0 NaN NaN NaN                     NaN
17119                 20         17.0 NaN NaN NaN                     NaN
17120                 20         17.0 NaN NaN NaN                     NaN
17121                 20         17.0 NaN NaN NaN                     NaN
17122                 20         17.0 NaN NaN NaN                     NaN

       Status_right Points
0          Finished   26.0
1          Finished   26.0
2          Finished   26.0
3          Finished   26.0
4          Finished   26.0
...             ...    ...
17118       +2 Laps    0.0
17119       +2 Laps    0.0
17120       +2 Laps    0.0
17121       +2 Laps    0.0
17122       +2 Laps    0.0

[17123 rows x 84 columns]

In [77]:
lap_data4.info(), lap_data4.describe(), lap_data4.describe(include='object')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17123 entries, 0 to 17122
Data columns (total 84 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   EventName           17123 non-null  object
 1   Time_x              17123 non-null  object
 2   Driver              17123 non-null  object
 3   DriverNumber_left   17123 non-null  int64
 4   LapTime             17010 non-null  object
 5   LapNumber           17123 non-null  float64
 6   Stint               17123 non-null  float64
 7   PitOutTime          554 non-null    object
 8   PitInTime           556 non-null    object
 9   Sector1Time         16788 non-null  object
 10  Sector2Time         17106 non-null  object
 11  Sector3Time         17083 non-null  object
 12  Sector1SessionTime  16750 non-null  object
 13  Sector2SessionTime  17106 non-null  object
 14  Sector3SessionTime  17083 non-null  object
 15  SpeedI1             14364 non-null  float64
 16  SpeedI2             17107 non-null  float64
 17  SpeedFL             16552 non-null  float64
 18  SpeedST             15833 non-null  float64
 19  IsPersonalBest      17115 non-null  object
 20  Compound            17123 non-null  object
 21  TyreLife            17123 non-null  float64
 22  FreshTyre           17123 non-null  bool
 23  Team                17123 non-null  object
 24  LapStartTime        17123 non-null  object
 25  LapStartDate        17115 non-null  object
 26  TrackStatus         17123 non-null  int64
 27  Position_left       17108 non-null  float64
 28  Deleted             17123 non-null  bool
 29  DeletedReason       173 non-null    object
 30  FastF1Generated     17123 non-null  bool
 31  IsAccurate          17123 non-null  bool
 32  Days_x              17123 non-null  int64
 33  Hours               17123 non-null  int64
 34  Minutes             17123 non-null  int64
 35  Time_y              17086 non-null  object
 36  AirTemp             17086 non-null  float64
 37  Humidity            17086 non-null  float64
 38  Pressure            17086 non-null  float64
 39  Rainfall            17086 non-null  object
 40  TrackTemp           17086 non-null  float64
 41  WindDirection       17086 non-null  float64
 42  WindSpeed           17086 non-null  float64
 43  Days_y              17086 non-null  float64
 44  Date_left           17123 non-null  object
 45  RPM                 17123 non-null  int64
 46  Speed               17123 non-null  int64
 47  nGear               17123 non-null  int64
 48  Throttle            17123 non-null  int64
 49  Brake               17123 non-null  bool
 50  DRS                 17123 non-null  int64
 51  Source_left         17123 non-null  object
 52  Time_left           17123 non-null  object
 53  SessionTime_left    17123 non-null  object
 54  Days_left           17123 non-null  int64
 55  Date_right          17123 non-null  object
 56  Status_left         17123 non-null  object
 57  X                   17123 non-null  float64
 58  Y                   17123 non-null  float64
 59  Z                   17123 non-null  float64
 60  Source_right        17123 non-null  object
 61  Time_right          17123 non-null  object
 62  SessionTime_right   17123 non-null  object
 63  Days_right          17123 non-null  int64
 64  DriverNumber_right  17123 non-null  int64
 65  BroadcastName       17123 non-null  object
 66  DriverId            17123 non-null  object
 67  TeamName            17123 non-null  object
 68  TeamColor           17123 non-null  object
 69  TeamId              17123 non-null  object
 70  FirstName           17123 non-null  object
 71  LastName            17123 non-null  object
 72  FullName            17123 non-null  object
 73  HeadshotUrl         17073 non-null  object
 74  CountryCode         17123 non-null  object
 75  Position_right      17123 non-null  float64
 76  ClassifiedPosition  17123 non-null  object
 77  GridPosition        17123 non-null  float64
 78  Q1                  0 non-null      float64
 79  Q2                  0 non-null      float64
 80  Q3                  0 non-null      float64
 81  Time                10681 non-null  object
 82  Status_right        17123 non-null  object
 83  Points              17123 non-null  float64
dtypes: bool(5), float64(24), int64(13), object(42)
memory usage: 10.4+ MB

(None,
        DriverNumber_left     LapNumber         Stint       SpeedI1  \
 count       17123.000000  17123.000000  17123.000000  14364.000000
 mean           27.785552     31.176079      2.096011    256.498816
 std            23.935130     18.652285      0.861789     41.524611
 min             1.000000      1.000000      1.000000     65.000000
 25%            11.000000     15.000000      1.000000    216.000000
 50%            22.000000     30.000000      2.000000    272.000000
 75%            44.000000     46.000000      3.000000    286.000000
 max            81.000000     78.000000      5.000000    357.000000

             SpeedI2       SpeedFL      SpeedST      TyreLife   TrackStatus  \
 count  17107.000000  16552.000000  15833.00000  17123.000000  17123.000000
 mean     248.072368    268.854459    296.23211     14.804006      6.322724
 std       40.018006     26.271023     27.24270     11.837362     63.464343
 min       57.000000      1.000000     65.00000      1.000000      1.000000
 25%      225.000000    255.000000    289.00000      6.000000      1.000000
 50%      256.000000    275.000000    300.00000     12.000000      1.000000
 75%      273.000000    282.000000    309.00000     20.000000      1.000000
 max      336.000000    330.000000    355.00000     78.000000   2671.000000

        Position_left  ...             Y             Z  Days_right  \
 count   17108.000000  ...  17123.000000  17123.000000     17123.0
 mean        9.917407  ...    991.381125   1480.730655         0.0
 std         5.501507  ...   6117.792796   2062.681439         0.0
 min         1.000000  ... -14882.000000   -159.000000         0.0
 25%         5.000000  ...  -2487.500000    148.000000         0.0
 50%        10.000000  ...    658.000000    555.000000         0.0
 75%        15.000000  ...   3854.500000   2006.000000         0.0
 max        20.000000  ...  21797.000000   7848.000000         0.0

        DriverNumber_right  Position_right  GridPosition   Q1   Q2   Q3  \
 count        17123.000000    17123.000000  17123.000000  0.0  0.0  0.0
 mean            27.785552        9.920925      9.796648  NaN  NaN  NaN
 std             23.935130        5.508342      5.706892  NaN  NaN  NaN
 min              1.000000        1.000000      0.000000  NaN  NaN  NaN
 25%             11.000000        5.000000      5.000000  NaN  NaN  NaN
 50%             22.000000       10.000000     10.000000  NaN  NaN  NaN
 75%             44.000000       15.000000     15.000000  NaN  NaN  NaN
 max             81.000000       20.000000     20.000000  NaN  NaN  NaN

              Points
 count  17123.000000
 mean       5.454243
 std        7.345619
 min        0.000000
 25%        0.000000
 50%        1.000000
 75%       10.000000
 max       26.000000

 [8 rows x 37 columns],
                EventName                  Time_x Driver  \
 count              17123                   17123  17123
 unique                15                   17097     21
 top     Dutch Grand Prix  0 days 01:36:02.379000    PIA
 freq                1426                       5    917

                        LapTime              PitOutTime  \
 count                    17010                     554
 unique                   13266                     554
 top     0 days 00:01:21.492000  0 days 01:27:55.379000
 freq                         7                       1

                      PitInTime             Sector1Time  \
 count                      556                   16788
 unique                     556                    9847
 top     0 days 01:27:30.291000  0 days 00:00:31.083000
 freq                         1                      12

                    Sector2Time             Sector3Time  \
 count                    17106                   17083
 unique                   10662                   10003
 top     0 days 00:00:18.093000  0 days 00:00:23.835000
 freq                         8                       9

             Sector1SessionTime  ... TeamColor   TeamId FirstName LastName  \
 count                    16750  ...     17123    17123     17123    17123
 unique                   16734  ...        19       10        21       21
 top     0 days 02:07:09.189000  ...    229971  mclaren     Oscar  Piastri
 freq                         2  ...      1778     1827       917      917

              FullName                                        HeadshotUrl  \
 count           17123                                              17073
 unique             21                                                 20
 top     Oscar Piastri  https://media.formula1.com/d_driver_fallback_i...
 freq              917                                                917

        CountryCode ClassifiedPosition                    Time Status_right
 count        17123              17123                   10681        17123
 unique          15                 23                     179           13
 top            GBR                  1  0 days 00:00:13.309000     Finished
 freq          2732                917                      78        10637

 [4 rows x 42 columns])

In [85]:
lap_data4['Date_left']

0        2024-03-02 15:04:42.550
1        2024-03-02 15:06:42.670
2        2024-03-02 15:07:42.550
3        2024-03-02 15:09:42.550
4        2024-03-02 15:11:42.510
                  ...
17118    2024-08-25 14:28:37.002
17119    2024-08-25 14:30:36.682
17120    2024-08-25 14:31:37.042
17121    2024-08-25 14:32:36.722
17122    2024-08-25 14:33:36.762
Name: Date_left, Length: 17123, dtype: object

In [87]:
lap_data4['Date_right']

0        2024-03-02 15:04:42.719
1        2024-03-02 15:06:42.499
2        2024-03-02 15:07:42.519
3        2024-03-02 15:09:42.459
4        2024-03-02 15:11:42.499
                  ...
17118    2024-08-25 14:28:36.796
17119    2024-08-25 14:30:36.736
17120    2024-08-25 14:31:37.177
17121    2024-08-25 14:32:36.657
17122    2024-08-25 14:33:36.717
Name: Date_right, Length: 17123, dtype: object

In [103]:
# Data Merge
# 3. control_message (Cancelled due to similar data from track_status)
# print(control_message_data)

In [89]:
# Data Merge
# 7. track_status
print(track_status_data)

              EventName                    Time  Status   Message
0    Bahrain Grand Prix  0 days 00:10:06.010000       1  AllClear
1    Bahrain Grand Prix  0 days 01:00:16.400000       2    Yellow
2    Bahrain Grand Prix  0 days 01:00:20.890000       1  AllClear
3    Bahrain Grand Prix  0 days 01:00:46.461000       2    Yellow
4    Bahrain Grand Prix  0 days 01:00:53.481000       1  AllClear
..                  ...                     ...     ...       ...
101  Belgian Grand Prix  0 days 01:22:18.736000       2    Yellow
102  Belgian Grand Prix  0 days 01:22:20.200000       1  AllClear
103    Dutch Grand Prix         0 days 00:00:00       1  AllClear
104    Dutch Grand Prix  0 days 00:14:41.553000       2    Yellow
105    Dutch Grand Prix  0 days 00:24:08.672000       1  AllClear

[106 rows x 4 columns]

In [91]:
track_status_data.head(20)

                   EventName                    Time  Status      Message
0         Bahrain Grand Prix  0 days 00:10:06.010000       1     AllClear
1         Bahrain Grand Prix  0 days 01:00:16.400000       2       Yellow
2         Bahrain Grand Prix  0 days 01:00:20.890000       1     AllClear
3         Bahrain Grand Prix  0 days 01:00:46.461000       2       Yellow
4         Bahrain Grand Prix  0 days 01:00:53.481000       1     AllClear
5         Bahrain Grand Prix  0 days 01:15:24.819000       2       Yellow
6         Bahrain Grand Prix  0 days 01:16:15.962000       1     AllClear
7   Saudi Arabian Grand Prix         0 days 00:00:00       2       Yellow
8   Saudi Arabian Grand Prix  0 days 00:08:45.692000       1     AllClear
9   Saudi Arabian Grand Prix  0 days 01:09:15.917000       2       Yellow
10  Saudi Arabian Grand Prix  0 days 01:09:49.924000       4   SCDeployed
11  Saudi Arabian Grand Prix  0 days 01:16:35.527000       1     AllClear
12     Australian Grand Prix         0 days 00:00:00       1     AllClear
13     Australian Grand Prix  0 days 00:00:13.560000       2       Yellow
14     Australian Grand Prix  0 days 00:05:52.010000       1     AllClear
15     Australian Grand Prix  0 days 01:21:24.717000       2       Yellow
16     Australian Grand Prix  0 days 01:21:41.517000       6  VSCDeployed
17     Australian Grand Prix  0 days 01:22:45.787000       7    VSCEnding
18     Australian Grand Prix  0 days 01:23:00.690000       1     AllClear
19     Australian Grand Prix  0 days 02:17:08.699000       2       Yellow

In [93]:
# track_status_data
# Extract days and hours
track_status_data['Days'] = track_status_data['Time'].apply(lambda x: int(x.split(' ')[0]))
track_status_data['Hours'] = track_status_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[0]))
track_status_data['Minutes'] = track_status_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[1]))

# View the updated DataFrame
print(track_status_data)

              EventName                    Time  Status   Message  Days  \
0    Bahrain Grand Prix  0 days 00:10:06.010000       1  AllClear     0
1    Bahrain Grand Prix  0 days 01:00:16.400000       2    Yellow     0
2    Bahrain Grand Prix  0 days 01:00:20.890000       1  AllClear     0
3    Bahrain Grand Prix  0 days 01:00:46.461000       2    Yellow     0
4    Bahrain Grand Prix  0 days 01:00:53.481000       1  AllClear     0
..                  ...                     ...     ...       ...   ...
101  Belgian Grand Prix  0 days 01:22:18.736000       2    Yellow     0
102  Belgian Grand Prix  0 days 01:22:20.200000       1  AllClear     0
103    Dutch Grand Prix         0 days 00:00:00       1  AllClear     0
104    Dutch Grand Prix  0 days 00:14:41.553000       2    Yellow     0
105    Dutch Grand Prix  0 days 00:24:08.672000       1  AllClear     0

     Hours  Minutes
0        0       10
1        1        0
2        1        0
3        1        0
4        1        0
..     ...      ...
101      1       22
102      1       22
103      0        0
104      0       14
105      0       24

[106 rows x 7 columns]

In [99]:
# Remove duplicates in track_status_data based on 'eventname' and 'hours'
track_status_data1 = track_status_data.drop_duplicates(subset=['EventName', 'Hours', 'Minutes'])

# Now perform the left join
lap_data5 = pd.merge(lap_data4, track_status_data1, on=['EventName', 'Hours', 'Minutes'], how='left', suffixes=('_left2', '_right2'))

# The number of rows in merged_df should now match df1

print(lap_data5)

                EventName                  Time_x Driver  DriverNumber_left  \
0      Bahrain Grand Prix  0 days 01:01:37.510000    VER                  1
1      Bahrain Grand Prix  0 days 01:03:13.806000    VER                  1
2      Bahrain Grand Prix  0 days 01:04:50.559000    VER                  1
3      Bahrain Grand Prix  0 days 01:06:27.206000    VER                  1
4      Bahrain Grand Prix  0 days 01:08:04.379000    VER                  1
...                   ...                     ...    ...                ...
17118    Dutch Grand Prix  0 days 02:23:52.192000    ZHO                 24
17119    Dutch Grand Prix  0 days 02:25:07.916000    ZHO                 24
17120    Dutch Grand Prix  0 days 02:26:25.673000    ZHO                 24
17121    Dutch Grand Prix  0 days 02:27:41.538000    ZHO                 24
17122    Dutch Grand Prix  0 days 02:28:57.336000    ZHO                 24

                      LapTime  LapNumber  Stint PitOutTime PitInTime  \
0      0 days 00:01:37.284000        1.0    1.0        NaN       NaN
1      0 days 00:01:36.296000        2.0    1.0        NaN       NaN
2      0 days 00:01:36.753000        3.0    1.0        NaN       NaN
3      0 days 00:01:36.647000        4.0    1.0        NaN       NaN
4      0 days 00:01:37.173000        5.0    1.0        NaN       NaN
...                       ...        ...    ...        ...       ...
17118  0 days 00:01:15.737000       66.0    3.0        NaN       NaN
17119  0 days 00:01:15.724000       67.0    3.0        NaN       NaN
17120  0 days 00:01:17.757000       68.0    3.0        NaN       NaN
17121  0 days 00:01:15.865000       69.0    3.0        NaN       NaN
17122  0 days 00:01:15.798000       70.0    3.0        NaN       NaN

                  Sector1Time  ...  Q1  Q2  Q3              Time_left2  \
0                         NaN  ... NaN NaN NaN  0 days 01:31:44.742000
1      0 days 00:00:30.916000  ... NaN NaN NaN  0 days 01:31:44.742000
2      0 days 00:00:30.999000  ... NaN NaN NaN  0 days 01:31:44.742000
3      0 days 00:00:30.931000  ... NaN NaN NaN  0 days 01:31:44.742000
4      0 days 00:00:31.255000  ... NaN NaN NaN  0 days 01:31:44.742000
...                       ...  ...  ..  ..  ..                     ...
17118  0 days 00:00:25.857000  ... NaN NaN NaN                     NaN
17119  0 days 00:00:25.746000  ... NaN NaN NaN                     NaN
17120  0 days 00:00:26.736000  ... NaN NaN NaN                     NaN
17121  0 days 00:00:25.980000  ... NaN NaN NaN                     NaN
17122  0 days 00:00:25.776000  ... NaN NaN NaN                     NaN

      Status_right  Points  Time_right2  Status  Message Days
0         Finished    26.0          NaN     NaN      NaN  NaN
1         Finished    26.0          NaN     NaN      NaN  NaN
2         Finished    26.0          NaN     NaN      NaN  NaN
3         Finished    26.0          NaN     NaN      NaN  NaN
4         Finished    26.0          NaN     NaN      NaN  NaN
...            ...     ...          ...     ...      ...  ...
17118      +2 Laps     0.0          NaN     NaN      NaN  NaN
17119      +2 Laps     0.0          NaN     NaN      NaN  NaN
17120      +2 Laps     0.0          NaN     NaN      NaN  NaN
17121      +2 Laps     0.0          NaN     NaN      NaN  NaN
17122      +2 Laps     0.0          NaN     NaN      NaN  NaN

[17123 rows x 88 columns]

In [101]:
lap_data5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17123 entries, 0 to 17122
Data columns (total 88 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   EventName           17123 non-null  object
 1   Time_x              17123 non-null  object
 2   Driver              17123 non-null  object
 3   DriverNumber_left   17123 non-null  int64
 4   LapTime             17010 non-null  object
 5   LapNumber           17123 non-null  float64
 6   Stint               17123 non-null  float64
 7   PitOutTime          554 non-null    object
 8   PitInTime           556 non-null    object
 9   Sector1Time         16788 non-null  object
 10  Sector2Time         17106 non-null  object
 11  Sector3Time         17083 non-null  object
 12  Sector1SessionTime  16750 non-null  object
 13  Sector2SessionTime  17106 non-null  object
 14  Sector3SessionTime  17083 non-null  object
 15  SpeedI1             14364 non-null  float64
 16  SpeedI2             17107 non-null  float64
 17  SpeedFL             16552 non-null  float64
 18  SpeedST             15833 non-null  float64
 19  IsPersonalBest      17115 non-null  object
 20  Compound            17123 non-null  object
 21  TyreLife            17123 non-null  float64
 22  FreshTyre           17123 non-null  bool
 23  Team                17123 non-null  object
 24  LapStartTime        17123 non-null  object
 25  LapStartDate        17115 non-null  object
 26  TrackStatus         17123 non-null  int64
 27  Position_left       17108 non-null  float64
 28  Deleted             17123 non-null  bool
 29  DeletedReason       173 non-null    object
 30  FastF1Generated     17123 non-null  bool
 31  IsAccurate          17123 non-null  bool
 32  Days_x              17123 non-null  int64
 33  Hours               17123 non-null  int64
 34  Minutes             17123 non-null  int64
 35  Time_y              17086 non-null  object
 36  AirTemp             17086 non-null  float64
 37  Humidity            17086 non-null  float64
 38  Pressure            17086 non-null  float64
 39  Rainfall            17086 non-null  object
 40  TrackTemp           17086 non-null  float64
 41  WindDirection       17086 non-null  float64
 42  WindSpeed           17086 non-null  float64
 43  Days_y              17086 non-null  float64
 44  Date_left           17123 non-null  object
 45  RPM                 17123 non-null  int64
 46  Speed               17123 non-null  int64
 47  nGear               17123 non-null  int64
 48  Throttle            17123 non-null  int64
 49  Brake               17123 non-null  bool
 50  DRS                 17123 non-null  int64
 51  Source_left         17123 non-null  object
 52  Time_left           17123 non-null  object
 53  SessionTime_left    17123 non-null  object
 54  Days_left           17123 non-null  int64
 55  Date_right          17123 non-null  object
 56  Status_left         17123 non-null  object
 57  X                   17123 non-null  float64
 58  Y                   17123 non-null  float64
 59  Z                   17123 non-null  float64
 60  Source_right        17123 non-null  object
 61  Time_right          17123 non-null  object
 62  SessionTime_right   17123 non-null  object
 63  Days_right          17123 non-null  int64
 64  DriverNumber_right  17123 non-null  int64
 65  BroadcastName       17123 non-null  object
 66  DriverId            17123 non-null  object
 67  TeamName            17123 non-null  object
 68  TeamColor           17123 non-null  object
 69  TeamId              17123 non-null  object
 70  FirstName           17123 non-null  object
 71  LastName            17123 non-null  object
 72  FullName            17123 non-null  object
 73  HeadshotUrl         17073 non-null  object
 74  CountryCode         17123 non-null  object
 75  Position_right      17123 non-null  float64
 76  ClassifiedPosition  17123 non-null  object
 77  GridPosition        17123 non-null  float64
 78  Q1                  0 non-null      float64
 79  Q2                  0 non-null      float64
 80  Q3                  0 non-null      float64
 81  Time_left2          10681 non-null  object
 82  Status_right        17123 non-null  object
 83  Points              17123 non-null  float64
 84  Time_right2         417 non-null    object
 85  Status              417 non-null    float64
 86  Message             417 non-null    object
 87  Days                417 non-null    float64
dtypes: bool(5), float64(26), int64(13), object(44)
memory usage: 10.9+ MB

In [107]:
# Data Merge
# 7. session_status_data
print(session_status_data)

             EventName                    Time     Status
0   Bahrain Grand Prix  0 days 00:00:09.193000   Inactive
1   Bahrain Grand Prix  0 days 00:59:59.911000    Started
2   Bahrain Grand Prix  0 days 02:31:44.878000   Finished
3   Bahrain Grand Prix  0 days 02:36:15.245000  Finalised
4   Bahrain Grand Prix  0 days 02:36:15.245000       Ends
..                 ...                     ...        ...
74    Dutch Grand Prix  0 days 00:00:07.915000   Inactive
75    Dutch Grand Prix  0 days 00:57:35.434000    Started
76    Dutch Grand Prix  0 days 02:28:21.209000   Finished
77    Dutch Grand Prix  0 days 02:32:46.284000  Finalised
78    Dutch Grand Prix  0 days 02:32:46.579000       Ends

[79 rows x 3 columns]

In [109]:
# session_status_data
# Extract days and hours
session_status_data['Days'] = session_status_data['Time'].apply(lambda x: int(x.split(' ')[0]))
session_status_data['Hours'] = session_status_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[0]))
session_status_data['Minutes'] = session_status_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[1]))

# View the updated DataFrame
print(session_status_data)

             EventName                    Time     Status  Days  Hours  \
0   Bahrain Grand Prix  0 days 00:00:09.193000   Inactive     0      0
1   Bahrain Grand Prix  0 days 00:59:59.911000    Started     0      0
2   Bahrain Grand Prix  0 days 02:31:44.878000   Finished     0      2
3   Bahrain Grand Prix  0 days 02:36:15.245000  Finalised     0      2
4   Bahrain Grand Prix  0 days 02:36:15.245000       Ends     0      2
..                 ...                     ...        ...   ...    ...
74    Dutch Grand Prix  0 days 00:00:07.915000   Inactive     0      0
75    Dutch Grand Prix  0 days 00:57:35.434000    Started     0      0
76    Dutch Grand Prix  0 days 02:28:21.209000   Finished     0      2
77    Dutch Grand Prix  0 days 02:32:46.284000  Finalised     0      2
78    Dutch Grand Prix  0 days 02:32:46.579000       Ends     0      2

    Minutes
0         0
1        59
2        31
3        36
4        36
..      ...
74        0
75       57
76       28
77       32
78       32

[79 rows x 6 columns]

In [111]:
# Remove duplicates in track_status_data based on 'eventname' and 'hours'
session_status_data1 = session_status_data.drop_duplicates(subset=['EventName', 'Hours', 'Minutes'])

# Now perform the left join
lap_data6 = pd.merge(lap_data5, session_status_data1, on=['EventName', 'Hours', 'Minutes'], how='left', suffixes=('_left3', '_right3'))

# The number of rows in merged_df should now match df1

print(lap_data6)

                EventName                  Time_x Driver  DriverNumber_left  \
0      Bahrain Grand Prix  0 days 01:01:37.510000    VER                  1
1      Bahrain Grand Prix  0 days 01:03:13.806000    VER                  1
2      Bahrain Grand Prix  0 days 01:04:50.559000    VER                  1
3      Bahrain Grand Prix  0 days 01:06:27.206000    VER                  1
4      Bahrain Grand Prix  0 days 01:08:04.379000    VER                  1
...                   ...                     ...    ...                ...
17118    Dutch Grand Prix  0 days 02:23:52.192000    ZHO                 24
17119    Dutch Grand Prix  0 days 02:25:07.916000    ZHO                 24
17120    Dutch Grand Prix  0 days 02:26:25.673000    ZHO                 24
17121    Dutch Grand Prix  0 days 02:27:41.538000    ZHO                 24
17122    Dutch Grand Prix  0 days 02:28:57.336000    ZHO                 24

                      LapTime  LapNumber  Stint PitOutTime PitInTime  \
0      0 days 00:01:37.284000        1.0    1.0        NaN       NaN
1      0 days 00:01:36.296000        2.0    1.0        NaN       NaN
2      0 days 00:01:36.753000        3.0    1.0        NaN       NaN
3      0 days 00:01:36.647000        4.0    1.0        NaN       NaN
4      0 days 00:01:37.173000        5.0    1.0        NaN       NaN
...                       ...        ...    ...        ...       ...
17118  0 days 00:01:15.737000       66.0    3.0        NaN       NaN
17119  0 days 00:01:15.724000       67.0    3.0        NaN       NaN
17120  0 days 00:01:17.757000       68.0    3.0        NaN       NaN
17121  0 days 00:01:15.865000       69.0    3.0        NaN       NaN
17122  0 days 00:01:15.798000       70.0    3.0        NaN       NaN

                  Sector1Time  ...              Time_left2 Status_right  \
0                         NaN  ...  0 days 01:31:44.742000     Finished
1      0 days 00:00:30.916000  ...  0 days 01:31:44.742000     Finished
2      0 days 00:00:30.999000  ...  0 days 01:31:44.742000     Finished
3      0 days 00:00:30.931000  ...  0 days 01:31:44.742000     Finished
4      0 days 00:00:31.255000  ...  0 days 01:31:44.742000     Finished
...                       ...  ...                     ...          ...
17118  0 days 00:00:25.857000  ...                     NaN      +2 Laps
17119  0 days 00:00:25.746000  ...                     NaN      +2 Laps
17120  0 days 00:00:26.736000  ...                     NaN      +2 Laps
17121  0 days 00:00:25.980000  ...                     NaN      +2 Laps
17122  0 days 00:00:25.776000  ...                     NaN      +2 Laps

      Points Time_right2 Status_left3  Message  Days_left3  \
0       26.0         NaN          NaN      NaN         NaN
1       26.0         NaN          NaN      NaN         NaN
2       26.0         NaN          NaN      NaN         NaN
3       26.0         NaN          NaN      NaN         NaN
4       26.0         NaN          NaN      NaN         NaN
...      ...         ...          ...      ...         ...
17118    0.0         NaN          NaN      NaN         NaN
17119    0.0         NaN          NaN      NaN         NaN
17120    0.0         NaN          NaN      NaN         NaN
17121    0.0         NaN          NaN      NaN         NaN
17122    0.0         NaN          NaN      NaN         NaN

                         Time  Status_right3 Days_right3
0                         NaN            NaN         NaN
1                         NaN            NaN         NaN
2                         NaN            NaN         NaN
3                         NaN            NaN         NaN
4                         NaN            NaN         NaN
...                       ...            ...         ...
17118                     NaN            NaN         NaN
17119                     NaN            NaN         NaN
17120                     NaN            NaN         NaN
17121                     NaN            NaN         NaN
17122  0 days 02:28:21.209000       Finished         0.0

[17123 rows x 91 columns]

In [113]:
lap_data6.info(), lap_data6.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17123 entries, 0 to 17122
Data columns (total 91 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   EventName           17123 non-null  object
 1   Time_x              17123 non-null  object
 2   Driver              17123 non-null  object
 3   DriverNumber_left   17123 non-null  int64
 4   LapTime             17010 non-null  object
 5   LapNumber           17123 non-null  float64
 6   Stint               17123 non-null  float64
 7   PitOutTime          554 non-null    object
 8   PitInTime           556 non-null    object
 9   Sector1Time         16788 non-null  object
 10  Sector2Time         17106 non-null  object
 11  Sector3Time         17083 non-null  object
 12  Sector1SessionTime  16750 non-null  object
 13  Sector2SessionTime  17106 non-null  object
 14  Sector3SessionTime  17083 non-null  object
 15  SpeedI1             14364 non-null  float64
 16  SpeedI2             17107 non-null  float64
 17  SpeedFL             16552 non-null  float64
 18  SpeedST             15833 non-null  float64
 19  IsPersonalBest      17115 non-null  object
 20  Compound            17123 non-null  object
 21  TyreLife            17123 non-null  float64
 22  FreshTyre           17123 non-null  bool
 23  Team                17123 non-null  object
 24  LapStartTime        17123 non-null  object
 25  LapStartDate        17115 non-null  object
 26  TrackStatus         17123 non-null  int64
 27  Position_left       17108 non-null  float64
 28  Deleted             17123 non-null  bool
 29  DeletedReason       173 non-null    object
 30  FastF1Generated     17123 non-null  bool
 31  IsAccurate          17123 non-null  bool
 32  Days_x              17123 non-null  int64
 33  Hours               17123 non-null  int64
 34  Minutes             17123 non-null  int64
 35  Time_y              17086 non-null  object
 36  AirTemp             17086 non-null  float64
 37  Humidity            17086 non-null  float64
 38  Pressure            17086 non-null  float64
 39  Rainfall            17086 non-null  object
 40  TrackTemp           17086 non-null  float64
 41  WindDirection       17086 non-null  float64
 42  WindSpeed           17086 non-null  float64
 43  Days_y              17086 non-null  float64
 44  Date_left           17123 non-null  object
 45  RPM                 17123 non-null  int64
 46  Speed               17123 non-null  int64
 47  nGear               17123 non-null  int64
 48  Throttle            17123 non-null  int64
 49  Brake               17123 non-null  bool
 50  DRS                 17123 non-null  int64
 51  Source_left         17123 non-null  object
 52  Time_left           17123 non-null  object
 53  SessionTime_left    17123 non-null  object
 54  Days_left           17123 non-null  int64
 55  Date_right          17123 non-null  object
 56  Status_left         17123 non-null  object
 57  X                   17123 non-null  float64
 58  Y                   17123 non-null  float64
 59  Z                   17123 non-null  float64
 60  Source_right        17123 non-null  object
 61  Time_right          17123 non-null  object
 62  SessionTime_right   17123 non-null  object
 63  Days_right          17123 non-null  int64
 64  DriverNumber_right  17123 non-null  int64
 65  BroadcastName       17123 non-null  object
 66  DriverId            17123 non-null  object
 67  TeamName            17123 non-null  object
 68  TeamColor           17123 non-null  object
 69  TeamId              17123 non-null  object
 70  FirstName           17123 non-null  object
 71  LastName            17123 non-null  object
 72  FullName            17123 non-null  object
 73  HeadshotUrl         17073 non-null  object
 74  CountryCode         17123 non-null  object
 75  Position_right      17123 non-null  float64
 76  ClassifiedPosition  17123 non-null  object
 77  GridPosition        17123 non-null  float64
 78  Q1                  0 non-null      float64
 79  Q2                  0 non-null      float64
 80  Q3                  0 non-null      float64
 81  Time_left2          10681 non-null  object
 82  Status_right        17123 non-null  object
 83  Points              17123 non-null  float64
 84  Time_right2         417 non-null    object
 85  Status_left3        417 non-null    float64
 86  Message             417 non-null    object
 87  Days_left3          417 non-null    float64
 88  Time                186 non-null    object
 89  Status_right3       186 non-null    object
 90  Days_right3         186 non-null    float64
dtypes: bool(5), float64(27), int64(13), object(46)
memory usage: 11.3+ MB

(None,
             EventName                  Time_x Driver  DriverNumber_left  \
 0  Bahrain Grand Prix  0 days 01:01:37.510000    VER                  1
 1  Bahrain Grand Prix  0 days 01:03:13.806000    VER                  1
 2  Bahrain Grand Prix  0 days 01:04:50.559000    VER                  1
 3  Bahrain Grand Prix  0 days 01:06:27.206000    VER                  1
 4  Bahrain Grand Prix  0 days 01:08:04.379000    VER                  1

                   LapTime  LapNumber  Stint PitOutTime PitInTime  \
 0  0 days 00:01:37.284000        1.0    1.0        NaN       NaN
 1  0 days 00:01:36.296000        2.0    1.0        NaN       NaN
 2  0 days 00:01:36.753000        3.0    1.0        NaN       NaN
 3  0 days 00:01:36.647000        4.0    1.0        NaN       NaN
 4  0 days 00:01:37.173000        5.0    1.0        NaN       NaN

               Sector1Time  ...              Time_left2 Status_right Points  \
 0                     NaN  ...  0 days 01:31:44.742000     Finished   26.0
 1  0 days 00:00:30.916000  ...  0 days 01:31:44.742000     Finished   26.0
 2  0 days 00:00:30.999000  ...  0 days 01:31:44.742000     Finished   26.0
 3  0 days 00:00:30.931000  ...  0 days 01:31:44.742000     Finished   26.0
 4  0 days 00:00:31.255000  ...  0 days 01:31:44.742000     Finished   26.0

   Time_right2 Status_left3  Message  Days_left3  Time  Status_right3  \
 0         NaN          NaN      NaN         NaN   NaN            NaN
 1         NaN          NaN      NaN         NaN   NaN            NaN
 2         NaN          NaN      NaN         NaN   NaN            NaN
 3         NaN          NaN      NaN         NaN   NaN            NaN
 4         NaN          NaN      NaN         NaN   NaN            NaN

   Days_right3
 0         NaN
 1         NaN
 2         NaN
 3         NaN
 4         NaN

 [5 rows x 91 columns])

In [115]:
# Save DataFrame to CSV
lap_data6.to_csv('all_data.csv', index=False)

In [ ]:
"""
# 2. circuit_data
# Extract days and hours
circuit_data['Days'] = circuit_data['Time'].apply(lambda x: int(x.split(' ')[0]))
circuit_data['Hours'] = circuit_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[0]))
circuit_data['Minutes'] = circuit_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[1]))

# View the updated DataFrame
print(circuit_data)
"""

In [ ]:
"""
# 3. control_message_data
# Extract days and hours
control_message_data['Days'] = control_message_data['Time'].apply(lambda x: int(x.split(' ')[0]))
control_message_data['Hours'] = control_message_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[0]))
control_message_data['Minutes'] = control_message_data['Time'].apply(lambda x: int(x.split(' ')[2].split(':')[1]))

# View the updated DataFrame
print(control_message_data)
"""